<script setup>
import { computed, inject, onBeforeUnmount, watch } from 'vue'
import { useRoute } from 'vue-router'
import { formatPublicPrice } from '@/utils/public-catalog.js'
const route = useRoute(); const { store } = inject('public-home-publication')
const modelKey = computed(() => String(route.params.modelKey || '')); const validModelKey = computed(() => /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(modelKey.value)); const slot = computed(() => validModelKey.value ? store.value.details[modelKey.value] || { status: 'loading', data: null } : { status: 'not_found', data: null })
const model = computed(() => slot.value.data?.model)
const load = () => validModelKey.value ? store.loadModel(modelKey.value) : Promise.resolve(null)
watch(modelKey, load, { immediate: true })
onBeforeUnmount(() => store.cancel(`detail:${modelKey.value}`))
const stableURL = computed(() => `/pricing/${encodeURIComponent(modelKey.value)}`)
</script>
<template><article class="pricing-detail"><RouterLink to="/pricing">← 返回模型价格</RouterLink><section v-if="slot.status === 'loading'" class="detail-state" role="status">正在加载已发布模型…</section><section v-else-if="slot.status === 'not_found'" class="detail-state" role="alert"><h1>模型不存在</h1><p>该 modelKey 未发布或不存在。</p></section><section v-else-if="slot.status === 'gone'" class="detail-state" role="alert"><h1>模型已下架</h1><p>该模型曾公开发布，当前已失效或删除，不再展示报价。</p></section><section v-else-if="slot.status === 'error'" class="detail-state" role="alert"><h1>模型目录暂时不可用</h1><p>这不代表模型不可调用，请稍后重试。</p><button class="public-button" type="button" @click="load">重试</button></section><template v-else-if="model"><header><p class="public-eyebrow">{{ model.provider }}</p><h1>{{ model.displayName }}</h1><code>{{ model.modelKey }}</code><span class="sr-only">稳定链接 {{ stableURL }}</span></header><div class="detail-prices"><section><h2>输入价格</h2><strong>{{ formatPublicPrice(model.inputPrice).label }}</strong><p v-if="model.inputPrice !== undefined">USD / 百万输入 Token</p></section><section><h2>输出价格</h2><strong>{{ formatPublicPrice(model.outputPrice).label }}</strong><p v-if="model.outputPrice !== undefined">USD / 百万输出 Token</p></section></div><p class="detail-disclaimer" role="note">模型参考报价，非自动扣费承诺；账户实际服务权益以套餐及控制台为准。</p><dl><div><dt>供应商</dt><dd>{{ model.provider }}</dd></div><div><dt>上下文窗口</dt><dd>{{ model.contextWindow.toLocaleString() }} Token</dd></div><div><dt>能力与端点</dt><dd><span v-for="item in model.capabilities" :key="item">{{ item }}</span></dd></div><div><dt>价格快照版本</dt><dd>{{ model.releaseVersion }}</dd></div></dl><RouterLink class="public-button" to="/chat">进入控制台</RouterLink></template></article></template>
<style scoped>.pricing-detail{width:min(920px,calc(100% - 48px));margin:0 auto;padding:64px 0 96px}.pricing-detail>header{margin:42px 0}.pricing-detail h1{font-size:clamp(36px,5vw,54px);margin:8px 0}.pricing-detail code{color:var(--public-muted)}.detail-prices{display:grid;grid-template-columns:1fr 1fr;gap:20px}.detail-prices section,.detail-state,.pricing-detail dl{padding:24px;border:1px solid var(--public-border);border-radius:16px;background:var(--public-card)}.detail-prices strong{font-family:ui-monospace,SFMono-Regular,monospace;font-size:32px}.detail-prices p{color:var(--public-muted)}.detail-disclaimer{margin:24px 0;padding:16px 20px;border-left:4px solid var(--public-primary);background:#eff6ff;color:#1e3a8a}.pricing-detail dl{display:grid;grid-template-columns:1fr 1fr;gap:20px}.pricing-detail dt{color:var(--public-muted)}.pricing-detail dd{margin:6px 0 0}.pricing-detail dd span{display:inline-block;margin-right:7px}.pricing-detail :focus-visible{outline:3px solid var(--public-primary);outline-offset:3px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:767px){.pricing-detail{width:calc(100% - 32px);padding-top:42px}.detail-prices,.pricing-detail dl{grid-template-columns:1fr}}/* 375px */@media(min-width:768px){.pricing-detail{max-width:920px}}/* 768px */@media(min-width:1440px){.pricing-detail{max-width:920px}}/* 1440px */</style>
