<script setup>
import { usePublicI18n } from '@/i18n/public-runtime.js'
import { publicPriceState } from '@/utils/public-pricing-query.js'
defineProps({ models: { type: Array, required: true } })
const linkFor = model => `/pricing/${encodeURIComponent(model.modelKey)}`
const { t } = usePublicI18n()
const price = (model, component) => { const state = publicPriceState(model, component); return { ...state, label: state.state === 'published' ? state.value : t(`pricingCatalog.${state.state === 'login_required' ? 'loginRequired' : 'unpublished'}`) } }
</script>
<template><div class="pricing-cards"><article v-for="model in models" :key="model.modelKey" class="pricing-card"><header><div><h2><RouterLink :to="linkFor(model)">{{ model.displayName }}</RouterLink></h2><code>{{ model.modelKey }}</code></div><span>{{ model.provider }}</span></header><dl><div class="pricing-card-price"><dt>{{ t('pricingCatalog.inputPrice') }}</dt><dd>{{ price(model,'input').label }}<small v-if="price(model,'input').state === 'published'">{{ t('pricingCatalog.unit') }}</small></dd></div><div class="pricing-card-price"><dt>{{ t('pricingCatalog.outputPrice') }}</dt><dd>{{ price(model,'output').label }}<small v-if="price(model,'output').state === 'published'">{{ t('pricingCatalog.unit') }}</small></dd></div></dl><p><span v-for="item in model.capabilities" :key="`cap-${item}`" class="pricing-tag">{{ item }}</span><span v-for="item in model.endpointTypes" :key="`endpoint-${item}`" class="pricing-tag">{{ item }}</span></p><small>{{ model.publicDisplayGroup || '—' }} · {{ model.updatedAt }}</small></article></div></template>
<style scoped>.pricing-cards{display:none;gap:12px}.pricing-card{padding:16px;border:1px solid var(--public-border);border-radius:10px;background:var(--public-card);box-shadow:0 1px 3px rgb(15 23 42 / 6%)}.pricing-card header{display:flex;justify-content:space-between;gap:14px}.pricing-card h2{margin:0;font-size:16px;line-height:1.3}.pricing-card h2 a{display:inline-flex;align-items:center;min-height:44px}.pricing-card code,.pricing-card header>span{color:var(--public-muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}.pricing-card dl{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.pricing-card dl>div{padding:10px;border-radius:10px;background:var(--public-bg)}.pricing-card dt{color:var(--public-muted);font-size:12px}.pricing-card dd{margin:5px 0 0;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:14px;font-weight:800}.pricing-card small{display:block;margin-top:4px;color:var(--public-muted);font-family:inherit;font-size:11px;font-weight:400}.pricing-tag{display:inline-block;margin:0 5px 5px 0;padding:3px 8px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:12px}.pricing-card a:focus-visible{outline:3px solid var(--public-primary);outline-offset:3px}@media(max-width:767px){.pricing-cards{display:grid}}/* 375px mobile acceptance */</style>
