<script setup>
import { usePublicI18n } from '@/i18n/public-runtime.js'
import { publicPriceState } from '@/utils/public-pricing-query.js'
defineProps({ models: { type: Array, required: true } })
const linkFor = model => `/pricing/${encodeURIComponent(model.modelKey)}`
const { t } = usePublicI18n()
const price = (model, component) => { const state = publicPriceState(model, component); return { ...state, label: state.state === 'published' ? state.value : t(`pricingCatalog.${state.state === 'login_required' ? 'loginRequired' : 'unpublished'}`) } }
</script>
<template><div class="pricing-table-wrap"><table class="pricing-table"><caption class="sr-only">{{ t('pricingCatalog.title') }}</caption><thead><tr><th scope="col">{{ t('pricingCatalog.model') }}</th><th scope="col">{{ t('pricingCatalog.provider') }}</th><th scope="col">{{ t('pricingCatalog.inputPrice') }}</th><th scope="col">{{ t('pricingCatalog.outputPrice') }}</th><th scope="col">{{ t('pricingCatalog.context') }}</th><th scope="col">{{ t('pricingCatalog.capability') }}</th><th scope="col">{{ t('pricingCatalog.endpoint') }}</th></tr></thead><tbody><tr v-for="model in models" :key="model.modelKey"><th scope="row"><RouterLink :to="linkFor(model)">{{ model.displayName }}</RouterLink><code>{{ model.modelKey }}</code><small>{{ model.publicDisplayGroup || '—' }} · {{ model.updatedAt }}</small></th><td>{{ model.provider }}</td><td><strong>{{ price(model,'input').label }}</strong><small v-if="price(model,'input').state === 'published'">{{ t('pricingCatalog.unit') }}</small></td><td><strong>{{ price(model,'output').label }}</strong><small v-if="price(model,'output').state === 'published'">{{ t('pricingCatalog.unit') }}</small></td><td>{{ model.contextWindow.toLocaleString() }} Token</td><td><span v-for="item in model.capabilities" :key="item" class="pricing-tag">{{ item }}</span></td><td><span v-for="item in model.endpointTypes" :key="item" class="pricing-tag">{{ item }}</span></td></tr></tbody></table></div></template>
<style scoped>.pricing-table-wrap{overflow:auto;border:1px solid var(--public-border);border-radius:10px;background:var(--public-card);box-shadow:0 1px 3px rgb(15 23 42 / 6%)}.pricing-table{width:100%;border-collapse:collapse;min-width:900px;font-size:13px}.pricing-table th,.pricing-table td{padding:10px 12px;text-align:left;border-bottom:1px solid var(--public-border);vertical-align:top}.pricing-table thead{background:color-mix(in srgb,var(--public-primary) 4%,var(--public-card))}.pricing-table thead th{color:var(--public-muted);font-size:12px;font-weight:700}.pricing-table tbody tr{transition:background-color .15s ease}.pricing-table tbody tr:hover{background:color-mix(in srgb,var(--public-primary) 3%,var(--public-card))}.pricing-table tbody tr:last-child>*{border-bottom:0}.pricing-table tbody th>a{display:inline-flex;align-items:center;min-height:44px}.pricing-table code,.pricing-table td strong{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-variant-numeric:tabular-nums}.pricing-table code,.pricing-table small{display:block;margin-top:3px;color:var(--public-muted);font-size:11px}.pricing-table a:focus-visible{outline:3px solid var(--public-primary);outline-offset:3px}.pricing-tag{display:inline-block;margin:0 5px 5px 0;padding:3px 8px;border-radius:999px;background:#eff6ff;color:#1d4ed8;font-size:12px}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}</style>
