import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')

test('root model routes and navigation fail closed', () => {
  const router = read('../router/index.js')
  const layout = read('../layouts/MainLayout.vue')
  assert.match(router, /path:\s*'\/admin\/public-models'/)
  assert.match(router, /path:\s*':guid'/)
  assert.match(router, /rootOnly:\s*true/)
  assert.match(router, /to\.meta\.rootOnly/)
  assert.match(router, /userStore\.user\?\.role\s*!==\s*'root'/)
  assert.match(layout, /user\.value\?\.role\s*===\s*'root'/)
  assert.match(layout, /index="\/admin\/public-models"/)
})

test('admin list exposes contract filters, missing sets and safe lifecycle actions', () => {
  const view = read('./PublicModelsAdmin.vue')
  const missing = read('../components/public-admin/MissingModelsPanel.vue')
  for (const token of ['search', 'status', 'upstreamState', 'completeness']) assert.match(view, new RegExp(token))
  assert.doesNotMatch(view, /filters\.(provider|capability|endpointType)/)
  assert.match(view, /value="complete"/)
  assert.match(view, /value="incomplete"/)
  assert.match(view, /const visibleItems=computed\(\(\)=>store\.items\)/)
  assert.match(view, /publicModelAdminRouteQuery\(filters\)/)
  assert.match(view, /resetPublicModelAdminPage\(filters\)/)
  assert.match(view, /loadMissing/)
  assert.match(view, /observedWithoutConfiguration/)
  assert.match(view, /MissingModelsPanel/)
  assert.match(view, /@create=/)
  assert.match(view, /<RouterLink[^>]+model-link/)
  assert.match(view, /sync/)
  assert.match(view, /mutationOperation==='sync'/)
  assert.match(view, /syncError\.requestId/)
  assert.doesNotMatch(view, /includeDeleted|['"]deleted['"]|restoreDeleted/i)
  assert.match(missing, /observedWithoutConfiguration/)
  assert.match(missing, /configuredMissingUpstream/)
})

test('model form preserves immutable identities and precise nullable prices', () => {
  const form = read('../components/public-admin/PublicModelForm.vue')
  assert.match(form, /mode === 'edit'/)
  assert.match(form, /modelKey[^\n]*disabled|disabled[^\n]*modelKey/)
  assert.match(form, /upstreamModelId[^\n]*disabled|disabled[^\n]*upstreamModelId/)
  assert.match(form, /inputPrice/)
  assert.match(form, /outputPrice/)
  assert.match(form, /priceSource/)
  assert.match(form, /priceReviewer/)
  assert.match(form, /priceEffectiveAt/)
  assert.doesNotMatch(form, /parseFloat|Number\(.*Price/)
})

test('detail handles revision conflicts and permanent verified soft deletion', () => {
  const view = read('./PublicModelDetail.vue')
  assert.match(view, /expectedRevision/)
  assert.match(view, /revision_conflict/)
  assert.match(view, /inputPrice:'inputPriceUsdPerMillionTokens'/)
  assert.match(view, /outputPrice:'outputPriceUsdPerMillionTokens'/)
  assert.match(view, /compareUnavailable/)
  assert.match(view, /:before-close="beforeDeleteClose"/)
  assert.match(view, /@update:model-value="deleteVisibility"/)
  assert.match(view, /aria-describedby="inactivation-reason-help"/)
  assert.match(view, /deleteForm\.reason\.trim\(\)/)
  assert.match(view, /deleteForm\.currentPassword\.trim\(\)/)
  assert.match(view, /id="delete-validation"/)
  assert.match(view, /loadDetail/)
  assert.match(view, /currentPassword/)
  assert.match(view, /autocomplete="current-password"/)
  assert.match(view, /permanent/i)
  assert.match(view, /el-dropdown/)
  assert.match(view, /deactivate/)
  assert.match(view, /activate/)
  assert.match(view, /remove/)
  assert.doesNotMatch(view, /restoreDeleted|restoreModel/i)
})

test('root model UI has bilingual copy and accessible responsive states', () => {
  const messages = read('../i18n/messages.js')
  const list = read('./PublicModelsAdmin.vue')
  const detail = read('./PublicModelDetail.vue')
  assert.ok((messages.match(/publicModelsAdmin:/g) || []).length >= 2)
  for (const source of [list, detail]) {
    assert.match(source, /aria-live|role="alert"/)
    assert.match(source, /loading/)
    assert.match(source, /error/)
    assert.match(source, /@media\s*\(max-width:/)
  }
})
