<template><main class="admin-page"><header><div><p class="eyebrow">ROOT ADMINISTRATION</p><h1 ref="heading" tabindex="-1">{{ t('publicModelsAdmin.title') }}</h1><p>{{ t('publicModelsAdmin.description') }}</p></div></header>
  <el-alert v-if="error" ref="errorAlert" role="alert" type="error" :closable="false" :title="errorMessage(error)"><p v-if="error.requestId">{{ t('publicModelsAdmin.requestId') }}: <code>{{ error.requestId }}</code></p><el-button link @click="load">{{ t('publicModelsAdmin.retry') }}</el-button></el-alert>
  <el-card class="filters"><el-form inline @submit.prevent="searchFromFirst"><el-form-item :label="t('publicModelsAdmin.search')"><el-input v-model="filters.search" clearable /></el-form-item><el-form-item :label="t('publicModelsAdmin.status')"><el-select v-model="filters.status" clearable><el-option v-for="s in ['draft','active','inactive']" :key="s" :label="t(`publicModelsAdmin.statuses.${s}`)" :value="s" /></el-select></el-form-item><el-form-item :label="t('publicModelsAdmin.upstreamState')"><el-select v-model="filters.upstreamState" clearable><el-option :label="t('publicModelsAdmin.present')" value="present"/><el-option :label="t('publicModelsAdmin.missing')" value="missing"/></el-select></el-form-item><el-button native-type="submit" type="primary">{{ t('publicModelsAdmin.search') }}</el-button></el-form></el-card>
  <el-table v-loading="loading" :data="visibleItems" row-key="guid" @row-click="openDetail"><el-table-column prop="displayName" :label="t('publicModelsAdmin.displayName')" min-width="160"/><el-table-column prop="modelKey" :label="t('publicModelsAdmin.modelKey')" min-width="160"><template #default="{row}"><code>{{ row.modelKey }}</code></template></el-table-column><el-table-column prop="provider" :label="t('publicModelsAdmin.provider')"/><el-table-column prop="status" :label="t('publicModelsAdmin.status')"><template #default="{row}"><el-tag>{{ t(`publicModelsAdmin.statuses.${row.status}`) }}</el-tag></template></el-table-column><el-table-column :label="t('publicModelsAdmin.completeness')"><template #default="{row}">{{ t(`publicModelsAdmin.${complete(row)?'complete':'incomplete'}`) }}</template></el-table-column><el-table-column :label="t('publicModelsAdmin.inputPrice')"><template #default="{row}">{{ price(row.inputPriceUsdPerMillionTokens) }}</template></el-table-column><el-table-column :label="t('publicModelsAdmin.outputPrice')"><template #default="{row}">{{ price(row.outputPriceUsdPerMillionTokens) }}</template></el-table-column></el-table>
  <p class="sr-only" aria-live="polite">{{ loading ? t('publicModelsAdmin.loading') : t('publicModelsAdmin.loaded', { count: visibleItems.length }) }}</p>
  <el-pagination v-model:current-page="filters.page" v-model:page-size="filters.pageSize" :total="total" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" @change="load" />
  <el-alert v-if="syncError" class="sync-error" role="alert" type="error" :closable="false" :title="errorMessage(syncError)"><p v-if="syncError.requestId">{{ t('publicModelsAdmin.requestId') }}: <code>{{ syncError.requestId }}</code></p></el-alert>
  <MissingModelsPanel :missing="missing" :loading="missingLoading" :syncing="syncSaving" :error="missingError" @sync="syncMissing" @create="openCreate" />
  <PublicModelForm v-model="showCreate" mode="create" :observed-ids="observedIds" :initial-upstream-id="selectedObservedId" :busy="createSaving" :error="formError" @submit="createModel" @closed="restoreFocus" />
</main></template>
<script setup>
import { computed,onBeforeUnmount,onMounted,reactive,ref,nextTick } from 'vue';import { useRouter } from 'vue-router';import { ElMessage } from 'element-plus';import { usePublicModelAdminStore } from '@/stores/publicModelAdmin';import { useI18n } from '@/composables/useI18n';import PublicModelForm from '@/components/public-admin/PublicModelForm.vue';import MissingModelsPanel from '@/components/public-admin/MissingModelsPanel.vue'
const store=usePublicModelAdminStore(),router=useRouter(),{t}=useI18n();const heading=ref(null),showCreate=ref(false),formError=ref(''),createTrigger=ref(null),selectedObservedId=ref('');const filters=reactive({search:'',status:'',upstreamState:'',page:1,pageSize:20});const loading=computed(()=>store.listLoading),error=computed(()=>store.listError),missing=computed(()=>store.missing),missingLoading=computed(()=>store.missingLoading),missingError=computed(()=>store.missingError),syncSaving=computed(()=>store.syncSaving),syncError=computed(()=>store.mutationOperation==='sync'?store.mutationError:null),createSaving=computed(()=>store.createSaving),total=computed(()=>store.total),observedIds=computed(()=>missing.value?.observedWithoutConfiguration??[])
const complete=m=>m.inputPriceUsdPerMillionTokens!==null&&m.outputPriceUsdPerMillionTokens!==null&&m.priceSource&&m.priceReviewer&&m.priceEffectiveAt!==null;const visibleItems=computed(()=>store.items)
const knownErrors=new Set(['authentication_required','root_required','not_found','gone','revision_conflict','validation_failed','unavailable','network_error']);const errorMessage=e=>t(`publicModelsAdmin.errors.${knownErrors.has(e?.code)?e.code:'request_failed'}`);const serverFilters=()=>({search:filters.search||undefined,status:filters.status||undefined,upstreamState:filters.upstreamState||undefined,page:filters.page,pageSize:filters.pageSize});async function load(){await store.load(serverFilters())}async function loadAll(){void load();void store.loadMissing()}function searchFromFirst(){filters.page=1;return load()}function openDetail(row){router.push(`/admin/public-models/${row.guid}`)}function openCreate(id,event){createTrigger.value=event?.currentTarget??document.activeElement;selectedObservedId.value=id;formError.value='';showCreate.value=true;nextTick(()=>{})}async function createModel(form){if(store.createSaving)return;formError.value='';const out=await store.create(form,new Set(observedIds.value));if(out){showCreate.value=false;void store.loadMissing();router.push(`/admin/public-models/${out.guid}`)}else formError.value=errorMessage(store.mutationError)}async function syncMissing(){if(store.syncSaving)return;const out=await store.sync();if(out){ElMessage.success(t('publicModelsAdmin.syncAccepted'));void store.loadMissing()}}function restoreFocus(){selectedObservedId.value='';nextTick(()=>createTrigger.value?.focus?.()??heading.value?.focus?.())}function price(v){return v===null?t('publicModelsAdmin.notSet'):`$${v}`};onMounted(()=>{store.setMutationContext('list');loadAll()});onBeforeUnmount(()=>store.cancel())
</script>
<style scoped>.admin-page{max-width:1400px;margin:auto;padding:24px;height:100%;overflow:auto}.eyebrow{letter-spacing:.12em;color:var(--text-secondary)}header,.filters,.el-alert,.el-table,.missing-panel{margin-bottom:20px}code{font-family:ui-monospace,monospace}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.el-pagination{margin:20px 0;justify-content:flex-end}@media(max-width:760px){.admin-page{padding:16px}.filters :deep(.el-form-item){display:block;margin-right:0}.el-pagination{justify-content:center;overflow:auto}}</style>
