<template><main class="page" ref="heading" tabindex="-1"><header><div><p class="eyebrow">ROOT</p><h1>{{ t('publicContentAdmin.title') }}</h1><p>{{ t('publicContentAdmin.description') }}</p></div><button type="button" @click="load">{{ t('publicContentAdmin.refresh') }}</button></header><p class="status" aria-live="polite">{{ status }}</p><section v-if="error" class="error" role="alert">{{ errorText }}<span v-if="error.requestId"> · {{ error.requestId }}</span></section><template v-if="draft"><nav class="tabs" aria-label="Content documents"><button v-for="name in names" :key="name" :aria-current="active===name?'page':undefined" @click="active=name">{{ t(`publicContentAdmin.documents.${name}`) }}</button></nav><SafeMarkdownEditor :id="`content-${active}`" v-model="draft[active]" :label="t(`publicContentAdmin.documents.${active}`)" :help="t('publicContentAdmin.markdownHelp')"/><label class="review"><input v-model="draft.legalReviewed" type="checkbox">{{ t('publicContentAdmin.legalReviewed') }}</label><div class="actions"><button type="button" :disabled="busy" @click="save">{{ t('publicContentAdmin.save') }}</button><button type="button" :disabled="busy" @click="openPreview">{{ t('publicContentAdmin.preview') }}</button><button type="button" :disabled="busy" @click="validate">{{ t('publicContentAdmin.validate') }}</button></div><section aria-labelledby="validation-title"><h2 id="validation-title">{{ t('publicContentAdmin.validation') }}</h2><p v-if="validation?.valid">{{ t('publicContentAdmin.valid') }}</p><ul v-else><li v-for="issue in validation?.issues??localIssues" :key="issue.field+issue.code"><code>{{ issue.code }}</code> · {{ issue.field }}</li></ul></section><section class="publish"><h2>{{ t('publicContentAdmin.publish') }}</h2><label>{{ t('publicContentAdmin.priceReleaseGuid') }}<input v-model.trim="priceReleaseGuid" inputmode="numeric"></label><label>{{ t('publicContentAdmin.currentPassword') }}<input ref="passwordInput" v-model="password" type="password" autocomplete="current-password"></label><button type="button" :disabled="busy||!validation?.valid||!password||!priceReleaseGuid" @click="publish">{{ t('publicContentAdmin.publish') }}</button><button v-if="pendingRecovery" type="button" @click="clearAttempt">{{ t('publicContentAdmin.reconcile') }}</button><p>{{ t('publicContentAdmin.productBlocker') }}</p></section><ContentReleaseHistory :items="history" :total="total" :busy="busy" @more="more" @restore="startRestore"/></template><dialog ref="restoreDialog" @close="restorePassword=''" @cancel.prevent="closeRestore"><h2>{{ t('publicContentAdmin.restore') }}</h2><p>{{ t('publicContentAdmin.restoreCreatesNew') }}</p><label>{{ t('publicContentAdmin.currentPassword') }}<input v-model="restorePassword" type="password" autocomplete="current-password"></label><button @click="restore">{{ t('publicContentAdmin.confirm') }}</button><button @click="closeRestore">{{ t('publicContentAdmin.cancel') }}</button></dialog></main></template>
<script setup>
import{computed,nextTick,onBeforeUnmount,onMounted,reactive,ref}from'vue';import{useRouter}from'vue-router';import{publicContentAdminApi,createIdempotencyKey}from'@/api/publicContentAdmin.js';import{publicPricingAdminApi}from'@/api/publicPricingAdmin.js';import{validatePublicContentDraft}from'@/utils/public-content-validation.js';import{useI18n}from'@/composables/useI18n';import SafeMarkdownEditor from'@/components/public-admin/SafeMarkdownEditor.vue';import ContentReleaseHistory from'@/components/public-admin/ContentReleaseHistory.vue';
const{t}=useI18n(),router=useRouter(),names=['home','about','terms','privacy'],active=ref('home'),draft=ref(null),validation=ref(null),history=ref([]),total=ref(0),page=ref(1),busy=ref(false),error=ref(null),priceReleaseGuid=ref(''),password=ref(''),restorePassword=ref(''),restoreTarget=ref(null),pendingRecovery=ref(false),attempt=ref(null),heading=ref(),passwordInput=ref(),restoreDialog=ref(),controller=ref(new AbortController()),generation=ref(0);const localIssues=computed(()=>draft.value?validatePublicContentDraft(draft.value).issues:[]),status=computed(()=>busy.value?t('publicContentAdmin.loading'):draft.value?t('publicContentAdmin.revision',{revision:draft.value.revision}):''),errorText=computed(()=>t(`publicContentAdmin.errors.${error.value?.code??'request_failed'}`));const safe=e=>({code:/^[a-z_]{1,64}$/.test(e?.code)?e.code:'request_failed',requestId:typeof e?.requestId==='string'?e.requestId:null});
async function guard(fn){const own=++generation.value;controller.value.abort();controller.value=new AbortController();busy.value=true;error.value=null;try{return await fn(controller.value.signal,own)}catch(e){if(e.name!=='AbortError'&&own===generation.value)error.value=safe(e);return null}finally{if(own===generation.value)busy.value=false}}
async function load(){attempt.value=null;pendingRecovery.value=false;await guard(async(signal,own)=>{const[d,h]=await Promise.all([publicContentAdminApi.getDraft({signal}),publicContentAdminApi.listReleases({page:1,pageSize:20,signal})]);if(own!==generation.value)return;draft.value=reactive({...d});history.value=h.items;total.value=h.total;page.value=1;validation.value=null})}
async function save(){if(busy.value)return;const out=await guard(signal=>publicContentAdminApi.saveDraft(draft.value,{signal}));if(out){draft.value=reactive({...out});validation.value=null}}
async function validate(){if(busy.value)return;let modelKeys=null;if(priceReleaseGuid.value){const release=await guard(signal=>publicPricingAdminApi.getRelease(priceReleaseGuid.value,{signal}));if(!release)return;modelKeys=release.items.map(x=>x.modelKey)}const local=validatePublicContentDraft(draft.value,{modelKeys});if(!local.valid){validation.value=local;return}validation.value=await guard(signal=>publicContentAdminApi.validate(draft.value.revision,{signal}))}
function openPreview(){const route=router.resolve({name:'PublicContentPreview',query:{revision:draft.value.revision}});window.open(route.href,'_blank','noopener,noreferrer')}
async function more(){const n=page.value+1,out=await guard(signal=>publicContentAdminApi.listReleases({page:n,pageSize:20,signal}));if(out){history.value.push(...out.items.filter(x=>!history.value.some(y=>y.guid===x.guid)));page.value=n}}
function newAttempt(kind,guid){return Object.freeze({kind,guid,revision:draft.value.revision,key:createIdempotencyKey()})}
async function publish(){if(busy.value)return;let secret=password.value;password.value='';if(!attempt.value)attempt.value=newAttempt('publish',priceReleaseGuid.value);const a=attempt.value;if(a.revision!==draft.value.revision){clearAttempt();error.value={code:'revision_conflict'};return}const out=await guard(async signal=>{const v=await publicContentAdminApi.issuePublishVerification(a.revision,secret,a.guid,{signal});secret='';return publicContentAdminApi.publish(a.revision,a.guid,{ticket:v.ticket,idempotencyKey:a.key,signal})});secret='';if(out){await load()}else if(error.value?.code==='network_error')pendingRecovery.value=true;await nextTick();passwordInput.value?.focus()}
function startRestore(item,event){restoreTarget.value={...item,trigger:event?.currentTarget};restorePassword.value='';restoreDialog.value?.showModal()}
function closeRestore(){restorePassword.value='';restoreDialog.value?.close();nextTick(()=>restoreTarget.value?.trigger?.focus());restoreTarget.value=null}
async function restore(){if(busy.value)return;let secret=restorePassword.value;restorePassword.value='';if(!attempt.value)attempt.value=newAttempt('restore',restoreTarget.value.guid);const a=attempt.value,out=await guard(async signal=>{const v=await publicContentAdminApi.issueRestoreVerification(a.guid,a.revision,secret,{signal});secret='';return publicContentAdminApi.restore(a.guid,a.revision,{ticket:v.ticket,idempotencyKey:a.key,signal})});secret='';if(out){closeRestore();await load()}else if(error.value?.code==='network_error')pendingRecovery.value=true}
function clearAttempt(){attempt.value=null;pendingRecovery.value=false;void load()}
onMounted(()=>{heading.value?.focus();void load()});onBeforeUnmount(()=>{password.value='';restorePassword.value='';attempt.value=null;controller.value.abort()})
</script>
<style scoped>.page{max-width:1200px;margin:auto;padding:24px;display:grid;gap:20px}.page>header{display:flex;justify-content:space-between;gap:16px}.eyebrow{letter-spacing:.12em}.tabs,.actions{display:flex;gap:8px;flex-wrap:wrap}.tabs button,.actions button,.page>header button,.publish button{min-height:44px}.review,.publish,.publish label{display:grid;gap:8px}.publish{padding:16px;border:1px solid var(--el-border-color);border-radius:12px}.publish input,dialog input{min-height:40px}.error{padding:12px;color:var(--el-color-danger);border:1px solid currentColor}.status{position:absolute;width:1px;height:1px;overflow:hidden}dialog{max-width:min(520px,calc(100vw - 32px))}@media(max-width:600px){.page{padding:16px}.page>header{flex-direction:column}}</style>
