import test,{afterEach}from'node:test'
import assert from'node:assert/strict'
import{readFile}from'node:fs/promises'
import{compileScript,compileTemplate,parse}from'@vue/compiler-sfc'
import{JSDOM}from'jsdom'
const dom=new JSDOM('<!doctype html><html><head></head><body></body></html>',{url:'https://local.test/admin/public-content'});for(const key of ['window','document','Document','navigator','Node','Element','HTMLElement','HTMLDialogElement','HTMLInputElement','SVGElement','Event','MouseEvent','KeyboardEvent','MutationObserver'])Object.defineProperty(globalThis,key,{configurable:true,writable:true,value:dom.window[key]});HTMLDialogElement.prototype.showModal=function(){this.open=true};HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new Event('close'))}
const[{mount},vue]=await Promise.all([import('@vue/test-utils'),import('vue')]);const{nextTick,reactive}=vue
afterEach(()=>{document.body.replaceChildren();for(const meta of document.head.querySelectorAll('meta[name="robots"]'))meta.remove();window.localStorage.clear();window.sessionStorage.clear();delete globalThis.__pcApi;delete globalThis.__pcPricing;delete globalThis.__pcRouter;delete globalThis.__pcUser;delete globalThis.open})
const data=code=>`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`
async function component(){const source=await readFile(new URL('./PublicContentAdmin.vue',import.meta.url),'utf8'),descriptor=parse(source,{filename:'PublicContentAdmin.vue'}).descriptor,script=compileScript(descriptor,{id:'pc-mounted',genDefaultAs:'__sfc__'}),template=compileTemplate({id:'pc-mounted',filename:'PublicContentAdmin.vue',source:descriptor.template.content,compilerOptions:{bindingMetadata:script.bindings}});assert.deepEqual(template.errors,[]);const actual=new URL('../api/publicContentAdmin.js',import.meta.url).href,validation=new URL('../utils/public-content-validation.js',import.meta.url).href,vueURL=new URL('../../node_modules/vue/index.mjs',import.meta.url).href
 const modules=new Map([
 ['vue',new URL('../../node_modules/vue/index.mjs',import.meta.url).href],
 ['vue-router',data("export const useRouter=()=>globalThis.__pcRouter")],
 ['@/api/publicContentAdmin.js',data(`import*as a from '${actual}';const p=new Proxy({}, {get:(_,k)=>(...v)=>globalThis.__pcApi[k](...v)});export const canonicalContentDraft=a.canonicalContentDraft,contentValidationProofMatches=a.contentValidationProofMatches,createContentValidationProof=a.createContentValidationProof;export const createContentPublicationCoordinator=o=>a.createContentPublicationCoordinator({...o,api:p,generateKey:()=> 'ik_'+('A'.repeat(42))+'Q'});export const publicContentAdminApi=p`)],
 ['@/api/publicPricingAdmin.js',data("export const publicPricingAdminApi=new Proxy({}, {get:(_,k)=>(...v)=>globalThis.__pcPricing[k](...v)})")],
 ['@/utils/public-content-validation.js',data(`import{validatePublicContentDraft as validate}from '${validation}';export const PUBLIC_CONTENT_APPROVAL_EVIDENCE=Object.freeze({approved:true,source:'mounted-test-signoff'});export const validatePublicContentDraft=(...a)=>validate(...a)`)],
 ['@/composables/useI18n',data("export const useI18n=()=>({t:(k,p)=>k+(p?.revision?':'+p.revision:'')})")],
 ['@/stores/user',data("export const useUserStore=()=>globalThis.__pcUser")],
 ['@/components/public-admin/SafeMarkdownEditor.vue',data(`import{defineComponent,h}from'${vueURL}';export default defineComponent({props:['modelValue','id','label','help'],emits:['update:modelValue'],setup(p,{emit}){return()=>h('textarea',{id:p.id,value:p.modelValue,onInput:e=>emit('update:modelValue',e.target.value)})}})`) ],
 ['@/components/public-admin/ContentReleaseHistory.vue',data(`import{defineComponent,h}from'${vueURL}';export default defineComponent({props:['items','total','busy','restoreDisabled'],emits:['more','restore'],setup(p,{emit}){return()=>h('section',[h('button',{id:'more',disabled:p.busy,onClick:()=>emit('more')},'more'),...(p.items||[]).map(x=>h('button',{class:'restore',disabled:p.restoreDisabled,onClick:e=>emit('restore',x,e)},x.guid))])}})`) ],
 ]);let code=`${script.content}\n${template.code}\n__sfc__.render=render\nexport default __sfc__`;for(const[from,to]of modules)code=code.replaceAll(`from '${from}'`,`from '${to}'`).replaceAll(`from'${from}'`,`from'${to}'`).replaceAll(`from "${from}"`,`from "${to}"`).replaceAll(`from"${from}"`,`from"${to}"`);return(await import(data(code))).default}
async function previewComponent(){const source=await readFile(new URL('./PublicContentPreview.vue',import.meta.url),'utf8'),descriptor=parse(source,{filename:'PublicContentPreview.vue'}).descriptor,script=compileScript(descriptor,{id:'preview-mounted',genDefaultAs:'__sfc__'}),template=compileTemplate({id:'preview-mounted',filename:'PublicContentPreview.vue',source:descriptor.template.content,compilerOptions:{bindingMetadata:script.bindings}});assert.deepEqual(template.errors,[]);const vueURL=new URL('../../node_modules/vue/index.mjs',import.meta.url).href,modules=new Map([
 ['vue',vueURL],
 ['vue-router',data("export const useRoute=()=>({query:{revision:'2'}})")],
 ['@/api/publicContentAdmin.js',data("export const publicContentAdminApi={preview:(...v)=>globalThis.__pcApi.preview(...v)}")],
 ['@/utils/public-content-validation.js',data("export const renderSafePublicMarkdown=v=>'<p>'+v.replace(/[<>&]/g,'')+'</p>'")],
 ['@/composables/useI18n',data("export const useI18n=()=>({t:k=>k})")],
 ]);let code=`${script.content}\n${template.code}\n__sfc__.render=render\nexport default __sfc__`;for(const[from,to]of modules)code=code.replaceAll(`from '${from}'`,`from '${to}'`).replaceAll(`from'${from}'`,`from'${to}'`).replaceAll(`from "${from}"`,`from "${to}"`).replaceAll(`from"${from}"`,`from"${to}"`);return(await import(data(code))).default}
const legal=title=>`# ${title}\n\nVersion: v1\n\nEffective Date: 2026-09-11\n\n## Body\nText\n\n## Contact\nsupport@example.com`,base={revision:2,home:'# Home',about:'# About',terms:legal('Terms'),privacy:legal('Privacy'),legalReviewed:true}
async function flush(){for(let i=0;i<8;i++)await nextTick();await new Promise(r=>setTimeout(r,0));await nextTick()}
async function waitFor(predicate){for(let i=0;i<100;i++){if(predicate())return;await new Promise(r=>setTimeout(r,1));await nextTick()}assert.fail('mounted condition did not settle')}
async function setup(overrides={}){globalThis.__pcUser=reactive({user:{role:'root'}});globalThis.__pcRouter={resolve:()=>({href:'/admin/public-content/preview?revision=2'}),replace:async value=>{globalThis.__pcRouter.replaced=value}};globalThis.open=()=>null;window.open=()=>null;const calls=[];globalThis.__pcApi={getDraft:async()=>({...base}),listReleases:async({page})=>({items:page===1?[{guid:'11',version:1,reason:'root_publish',sourceRevision:2,createdAt:'2026-09-11T00:00:00Z'}]:[{guid:'12',version:2,reason:'restore',sourceRevision:2,createdAt:'2026-09-11T01:00:00Z'}],page,pageSize:20,total:2}),saveDraft:async v=>({...v,revision:v.revision+1}),validate:async()=>({valid:true,issues:[]}),issuePublishVerification:async()=>({ticket:'ticket'}),publish:async(...a)=>(calls.push(['publish',...a]),{guid:'20'}),issueRestoreVerification:async()=>({ticket:'ticket'}),restore:async(...a)=>(calls.push(['restore',...a]),{guid:'21'}),...overrides};globalThis.__pcPricing={getRelease:async()=>({items:[{modelKey:'model-a'}]})};const C=await component(),wrapper=mount(C,{attachTo:document.body});await flush();return{wrapper,calls}}
async function establish(wrapper){await wrapper.get('input[inputmode="numeric"]').setValue('7');await flush();await wrapper.findAll('button').find(x=>x.text().includes('validate')).trigger('click');await waitFor(()=>wrapper.vm.validationProof?.valid===true)}
test('mounted edits review and price changes invalidate proof and unsaved content blocks preview',async()=>{const{wrapper}=await setup();const password=wrapper.get('input[autocomplete="current-password"]'),publish=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.publish'),preview=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.preview');await establish(wrapper);await password.setValue('secret');await flush();assert.equal(publish.attributes('disabled'),undefined);await wrapper.get('textarea').setValue('# changed');await flush();assert.notEqual(publish.attributes('disabled'),undefined);assert.notEqual(preview.attributes('disabled'),undefined);await wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.save').trigger('click');await flush();await establish(wrapper);await password.setValue('secret');await flush();await wrapper.get('input[type="checkbox"]').setValue(false);await flush();assert.notEqual(publish.attributes('disabled'),undefined);await wrapper.get('input[type="checkbox"]').setValue(true);await flush();await wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.save').trigger('click');await flush();await establish(wrapper);await password.setValue('secret');await flush();await wrapper.get('input[inputmode="numeric"]').setValue('8');await flush();assert.notEqual(publish.attributes('disabled'),undefined);wrapper.unmount()})
test('mounted double click shares one issue and demotion clears privileged state before redirect',async()=>{let resolve,issues=0,executes=0;const{wrapper}=await setup({issuePublishVerification:()=>{issues++;return new Promise(r=>resolve=r)},publish:async()=>{executes++}});await establish(wrapper);const password=wrapper.get('input[autocomplete="current-password"]');await password.setValue('secret');await flush();const publish=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.publish');publish.element.click();publish.element.click();await waitFor(()=>issues===1);globalThis.__pcUser.user.role='admin';assert.equal(wrapper.vm.draft,null);assert.deepEqual(wrapper.vm.history,[]);assert.equal(wrapper.vm.total,0);assert.equal(wrapper.vm.savedCanonical,null);assert.equal(wrapper.vm.restoreTarget,null);assert.deepEqual(globalThis.__pcRouter.replaced,{path:'/chat',replace:true});await nextTick();resolve({ticket:'late'});await flush();assert.equal(executes,0);assert.equal(wrapper.find('textarea').exists(),false);wrapper.unmount()})
test('demotion rejects late save and validation responses that ignore abort',async()=>{let resolveSave,resolveRelease;const{wrapper}=await setup({saveDraft:()=>new Promise(r=>resolveSave=r)});const save=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.save');await save.trigger('click');globalThis.__pcUser.user.role='admin';resolveSave({...base,revision:99,home:'# leaked'});await flush();assert.equal(wrapper.vm.draft,null);assert.equal(wrapper.vm.savedCanonical,null);wrapper.unmount();const second=await setup();await second.wrapper.get('input[inputmode="numeric"]').setValue('7');globalThis.__pcPricing.getRelease=()=>new Promise(r=>resolveRelease=r);await second.wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.validate').trigger('click');globalThis.__pcUser.user.role='admin';resolveRelease({items:[{modelKey:'model-a'}]});await flush();assert.equal(second.wrapper.vm.draft,null);assert.deepEqual(second.wrapper.vm.localIssues,[]);assert.equal(second.wrapper.vm.validationProof,null);second.wrapper.unmount()})
test('demotion rejects late draft and history responses that ignore abort',async()=>{let resolveDraft,resolveHistory,draftReads=0;const{wrapper}=await setup({getDraft:()=>++draftReads===1?Promise.resolve({...base}):new Promise(r=>resolveDraft=r),listReleases:({page})=>page===1?Promise.resolve({items:[{guid:'11',version:1,reason:'root_publish',sourceRevision:2,createdAt:'2026-09-11T00:00:00Z'}],page:1,pageSize:20,total:2}):new Promise(r=>resolveHistory=r)});await wrapper.get('#more').trigger('click');await wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.refresh').trigger('click');globalThis.__pcUser.user.role='admin';resolveDraft({...base,revision:88,home:'# leaked'});resolveHistory({items:[{guid:'99',version:9,reason:'restore',sourceRevision:2,createdAt:'2026-09-11T00:00:00Z'}],page:2,pageSize:20,total:2});await flush();assert.equal(wrapper.vm.draft,null);assert.deepEqual(wrapper.vm.history,[]);assert.equal(wrapper.vm.total,0);wrapper.unmount()})
test('mounted execute ambiguity retries one binding and reconcile abandons it',async()=>{let execute=0;const{wrapper}=await setup({publish:async()=>{execute++;throw{code:'network_error'}}});await establish(wrapper);const password=wrapper.get('input[autocomplete="current-password"]'),publish=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.publish');await password.setValue('one');await publish.trigger('click');await flush();assert.equal(execute,1);await password.setValue('two');await publish.trigger('click');await flush();assert.equal(execute,2);const reconcile=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.reconcile');await reconcile.trigger('click');await flush();assert.equal(wrapper.findAll('button').some(x=>x.text()==='publicContentAdmin.reconcile'),false);wrapper.unmount()})
test('mounted 409 reloads the current saved revision for comparison',async()=>{let reads=0;const{wrapper}=await setup({getDraft:async()=>({...base,revision:++reads===1?2:3}),publish:async()=>{throw{code:'revision_conflict'}}});await establish(wrapper);await wrapper.get('input[autocomplete="current-password"]').setValue('secret');await flush();await wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.publish').trigger('click');await flush();assert.match(wrapper.get('.status').text(),/:3$/);assert.equal(reads,2);wrapper.unmount()})
test('mounted history pagination rejects stale ownership and restore dialog handles Escape focus',async()=>{let resolvePage;const listReleases=({page})=>page===1?Promise.resolve({items:[{guid:'11',version:1,reason:'root_publish',sourceRevision:2,createdAt:'2026-09-11T00:00:00Z'}],page:1,pageSize:20,total:2}):new Promise(r=>resolvePage=r);const{wrapper}=await setup({listReleases});const more=wrapper.get('#more');await more.trigger('click');const refresh=wrapper.findAll('button').find(x=>x.text()==='publicContentAdmin.refresh');await refresh.trigger('click');resolvePage?.({items:[{guid:'12',version:2,reason:'restore',sourceRevision:2,createdAt:'2026-09-11T00:00:00Z'}],page:2,pageSize:20,total:2});await flush();assert.equal(wrapper.findAll('.restore').some(x=>x.text()==='12'),false);const restore=wrapper.get('.restore');restore.element.focus();await restore.trigger('click');await flush();const dialog=wrapper.get('dialog');assert.equal(dialog.attributes('aria-labelledby'),'restore-content-title');dialog.element.dispatchEvent(new Event('cancel',{cancelable:true}));await flush();assert.equal(document.activeElement,restore.element);wrapper.unmount()})
test('mounted preview installs robots metadata and removes it on unmount',async()=>{globalThis.__pcApi={preview:async()=>({revision:2,documents:{home:'# Home',about:'About',terms:'Terms',privacy:'Privacy'}})};const C=await previewComponent(),wrapper=mount(C,{attachTo:document.body});await flush();const robots=document.head.querySelector('meta[name="robots"]');assert.equal(robots?.content,'noindex, nofollow, noarchive');assert.match(wrapper.get('article').html(),/Home/);wrapper.unmount();assert.equal(document.head.querySelector('meta[name="robots"]'),null)})
