import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{compileScript,compileTemplate,parse}from'@vue/compiler-sfc';import{JSDOM}from'jsdom'
const data=source=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`,dom=new JSDOM('<!doctype html><html><body></body></html>');for(const key of['window','document','navigator','Node','Element','HTMLElement','SVGElement'])Object.defineProperty(globalThis,key,{configurable:true,value:dom.window[key]})
const vueURL=new URL('../../node_modules/vue/index.mjs',import.meta.url).href,i18n=data("export const useI18n=()=>({t:(key,args)=>key+(args?JSON.stringify(args):'')})"),store=data("export const useRootNotificationsStore=()=>globalThis.__rootNotificationsStore"),shell=data(`import{defineComponent,h}from'${vueURL}';export default defineComponent({inheritAttrs:false,setup(_,{attrs,slots}){return()=>h('section',attrs,[attrs.label,slots.default?.(),slots.actions?.()])}})`)
const source=await readFile(new URL('./RootNotifications.vue',import.meta.url),'utf8'),descriptor=parse(source,{filename:'RootNotifications.vue'}).descriptor,script=compileScript(descriptor,{id:'root-notifications-mounted',genDefaultAs:'__sfc__'}),template=compileTemplate({id:'root-notifications-mounted',filename:'RootNotifications.vue',source:descriptor.template.content,compilerOptions:{bindingMetadata:script.bindings}});assert.deepEqual(template.errors,[]);let code=`${script.content}\n${template.code}\n__sfc__.render=render\nexport default __sfc__`;for(const[from,to]of[['vue',vueURL],['@/composables/useI18n',i18n],['@/stores/rootNotifications',store],['@/components/shell/PageHeader.vue',shell],['@/components/shell/SurfaceCard.vue',shell],['@/components/shell/StatusBadge.vue',shell]])code=code.replaceAll(`from'${from}'`,`from'${to}'`).replaceAll(`from '${from}'`,`from '${to}'`).replaceAll(`from "${from}"`,`from "${to}"`);const View=(await import(data(code))).default
const[{mount},{defineComponent,h,reactive,nextTick}]=await Promise.all([import('@vue/test-utils'),import('vue')]),Pass=defineComponent({setup(_,{slots}){return()=>h('div',slots.default?.())}}),Button=defineComponent({inheritAttrs:false,setup(_,{attrs,slots}){return()=>h('button',{...attrs,disabled:attrs.disabled,onClick:attrs.onClick},slots.default?.())}})
test('mounted inbox independently loads more active and resolved groups with accessible controls',async()=>{const calls=[],item=(guid,state)=>({guid,type:'upstream_missing',state,read:false,acknowledged:false,updatedAt:1720000000000}),store=reactive({active:[item('101','active')],resolved:[item('201','resolved')],activeTotal:2,resolvedTotal:2,activeLoadingMore:false,resolvedLoadingMore:false,unreadCount:2,loading:false,error:null,mutationError:null,pendingReceipts:{},refresh(){},markRead(){},acknowledge(){},loadMore(state){calls.push(state)}});globalThis.__rootNotificationsStore=store;const wrapper=mount(View,{global:{stubs:{ElButton:Button,ElAlert:Pass,ElTag:Pass}}});for(const state of['active','resolved']){const button=wrapper.get(`#load-more-${state}`);assert.equal(button.attributes('aria-controls'),`notification-list-${state}`);await button.trigger('click')}await nextTick();assert.deepEqual(calls,['active','resolved']);store.active.push(item('102','active'));await nextTick();assert.equal(wrapper.find('#load-more-active').exists(),false);assert.equal(wrapper.find('#load-more-resolved').exists(),true);wrapper.unmount()})

test('mounted notification shell exposes read state and a non-interactive email delivery todo',async()=>{
 const store=reactive({active:[{guid:'301',type:'upstream_missing',state:'active',read:false,acknowledged:false,updatedAt:1720000000000}],resolved:[],activeTotal:1,resolvedTotal:0,activeLoadingMore:false,resolvedLoadingMore:false,unreadCount:1,loading:false,error:null,mutationError:null,pendingReceipts:{},refresh(){},markRead(){},acknowledge(){},loadMore(){}})
 globalThis.__rootNotificationsStore=store;const wrapper=mount(View,{global:{stubs:{ElButton:Button,ElAlert:Pass,ElTag:Pass}}});assert.match(wrapper.text(),/Email push.*TODO/i);assert.equal(wrapper.find('.email-delivery-todo button').exists(),false);assert.match(wrapper.text(),/rootNotifications\.unreadState/);wrapper.unmount()
})
