const GUID=/^[1-9]\d{0,18}$/,MAX_GUID='9223372036854775807',OPAQUE=/^(?:av|ik)_[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/,CODE=/^[a-z][a-z0-9_-]{0,63}$/,RFC3339=/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z$/
const DRAFT_KEYS=['revision','home','about','terms','privacy','legal_reviewed'],RELEASE_KEYS=['guid','version','reason','source_revision','created_at']
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)!==null&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k))
const positive=v=>Number.isSafeInteger(v)&&v>=1
const header=(h,n)=>{const v=typeof h?.get==='function'?h.get(n):h?.[n]??h?.[n.toLowerCase()];return typeof v==='string'?v:null}
const validGuid=v=>typeof v==='string'&&GUID.test(v)&&(v.length<MAX_GUID.length||v.length===MAX_GUID.length&&v<=MAX_GUID)
const requestError=()=>{throw new Error('invalid_public_content_admin_request')}
class InvalidResponse extends Error{constructor(){super('invalid_public_content_admin_response')}}
const invalid=()=>{throw new InvalidResponse()}
function metadata(result,status,{preview=false}={}){if(!exact(result,['data','status','headers'])||result.status!==status||header(result.headers,'Cache-Control')!=='no-store'||!header(result.headers,'X-Request-ID')?.trim()||(preview&&header(result.headers,'X-Robots-Tag')!=='noindex, nofollow'))invalid();return result.data}
function revision(v){if(!positive(v))requestError();return v}
function guid(v){v=String(v);if(!validGuid(v))requestError();return encodeURIComponent(v)}
function opaque(v,prefix){if(typeof v!=='string'||!OPAQUE.test(v)||!v.startsWith(prefix))requestError();return v}
function cleanText(v,max=262144){return typeof v==='string'&&v.length<=max&&!/[\u0000]/.test(v)}
function draft(raw){if(!exact(raw,DRAFT_KEYS)||!positive(raw.revision)||!cleanText(raw.home)||!cleanText(raw.about)||!cleanText(raw.terms)||!cleanText(raw.privacy)||typeof raw.legal_reviewed!=='boolean')invalid();return Object.freeze({revision:raw.revision,home:raw.home,about:raw.about,terms:raw.terms,privacy:raw.privacy,legalReviewed:raw.legal_reviewed})}
function utc(v){if(typeof v!=='string'||!RFC3339.test(v))return false;const ms=Date.parse(v);return Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,19)===v.slice(0,19)}
function release(raw){if(!exact(raw,RELEASE_KEYS)||!validGuid(raw.guid)||!positive(raw.version)||!['root_publish','restore'].includes(raw.reason)||!positive(raw.source_revision)||!utc(raw.created_at))invalid();return Object.freeze({guid:raw.guid,version:raw.version,reason:raw.reason,sourceRevision:raw.source_revision,createdAt:raw.created_at})}
function mapIssue(raw){if(!exact(raw,['field','code'])||typeof raw.field!=='string'||!raw.field||!CODE.test(raw.code))invalid();return Object.freeze({field:raw.field,code:raw.code})}
export class PublicContentAdminError extends Error{constructor(code,status=null,requestId=null){super(code);this.name='PublicContentAdminError';Object.assign(this,{code,status,requestId})}}
function mapError(e){if(e?.name==='AbortError')return e;const status=Number.isInteger(e?.response?.status)?e.response.status:null,raw=e?.response?.data,rid=header(e?.response?.headers,'X-Request-ID'),expected=({400:'invalid_request',401:'authentication_required',403:'root_role_required',404:'not_found',409:'conflict',410:'gone',422:'validation_failed',503:'unavailable'})[status];const valid=expected&&header(e?.response?.headers,'Cache-Control')==='no-store'&&rid?.trim()&&exact(raw,['error'])&&exact(raw.error,['code','message','request_id'])&&raw.error.code===expected&&raw.error.request_id===rid&&typeof raw.error.message==='string';if(!valid)return new PublicContentAdminError(status?'request_failed':'network_error',status);return new PublicContentAdminError(status===409?'revision_conflict':status===403?'root_required':expected,status,rid)}
const VERIFY=new Map([[400,new Set(['invalid_admin_action_request'])],[403,new Set(['action_verification_rejected'])],[409,new Set(['action_verification_conflict'])],[422,new Set(['action_inactive'])],[429,new Set(['action_rate_limited'])],[503,new Set(['action_dependency_unavailable'])]])
function mapVerifyError(e){if(e?.name==='AbortError')return e;const status=e?.response?.status,raw=e?.response?.data,rid=header(e?.response?.headers,'X-Request-ID'),p=raw?.error;const valid=header(e?.response?.headers,'Cache-Control')==='no-store'&&rid?.trim()&&exact(raw,['error'])&&exact(p,['code','message','type','request_id'])&&p.type==='admin_action_error'&&p.request_id===rid&&VERIFY.get(status)?.has(p.code);return valid?new PublicContentAdminError(p.code,status,rid):new PublicContentAdminError(status?'request_failed':'network_error',status)}
export function createPublicContentAdminProductionRequest({get,mutation,actionPost}={}){return async a=>a.method==='GET'?get(a.path,{signal:a.signal}):a.method==='PUT'?mutation({method:'PUT',path:a.path,body:a.body,signal:a.signal}):a.method==='POST'?actionPost(a.path,a.body,{headers:a.headers,signal:a.signal}):requestError()}
async function productionRequest(a){const {authenticatedFetch,adminActionPost,default:req}=await import('./request.js'),base=import.meta.env?.VITE_API_BASE??'';return createPublicContentAdminProductionRequest({get:async(path,o)=>{const r=await authenticatedFetch(base+path,{method:'GET',signal:o.signal});let data;try{data=await r.json()}catch{}const x={data,status:r.status,headers:r.headers};if(!r.ok)throw{response:x};return x},mutation:async x=>{const r=await req.request({method:x.method,url:x.path,data:x.body,signal:x.signal});return{data:r.data,status:r.status,headers:r.headers}},actionPost:adminActionPost})(a)}
export function createPublicContentAdminApi({request=productionRequest}={}){const run=async(a,status,mapper,opts)=>{try{return mapper(metadata(await request(a),status,opts))}catch(e){if(e instanceof InvalidResponse)throw e;throw mapError(e)}};const verify=async(action,intent,password,o={})=>{if(typeof password!=='string'||!password||/[\u0000-\u001f\u007f]/.test(password))requestError();try{const raw=metadata(await request({method:'POST',path:'/admin/v2/action-verifications',body:{action,intent,current_password:password},signal:o.signal}),201);if(!exact(raw,['ticket','expires_at'])||!OPAQUE.test(raw.ticket)||!raw.ticket.startsWith('av_')||!positive(raw.expires_at))invalid();return Object.freeze({ticket:raw.ticket,expiresAt:raw.expires_at})}catch(e){if(e instanceof InvalidResponse)throw e;throw mapVerifyError(e)}};const action=(path,body,o)=>{if(!o||Object.keys(o).some(k=>!['ticket','idempotencyKey','signal'].includes(k)))requestError();return run({method:'POST',path,body,headers:{'Idempotency-Key':opaque(o.idempotencyKey,'ik_'),'X-Action-Ticket':opaque(o.ticket,'av_')},signal:o.signal},201,release)};return Object.freeze({
 getDraft:(o={})=>run({method:'GET',path:'/admin/v2/public-content/draft',signal:o.signal},200,draft),
 saveDraft:(value,o={})=>{if(!value||Object.keys(value).some(k=>!['revision','home','about','terms','privacy','legalReviewed'].includes(k))||!positive(value.revision)||![value.home,value.about,value.terms,value.privacy].every(x=>cleanText(x))||typeof value.legalReviewed!=='boolean')requestError();return run({method:'PUT',path:'/admin/v2/public-content/draft',body:{expected_revision:value.revision,home:value.home,about:value.about,terms:value.terms,privacy:value.privacy,legal_reviewed:value.legalReviewed},signal:o.signal},200,draft)},
 validate:(rev,o={})=>run({method:'POST',path:'/admin/v2/public-content/validate',body:{expected_revision:revision(rev)},signal:o.signal},200,raw=>{if(!exact(raw,['valid','issues'])||typeof raw.valid!=='boolean'||!Array.isArray(raw.issues))invalid();return Object.freeze({valid:raw.valid,issues:Object.freeze(raw.issues.map(mapIssue))})}),
 preview:(rev,o={})=>run({method:'GET',path:`/admin/v2/public-content/preview?revision=${revision(rev)}`,signal:o.signal},200,raw=>{if(!exact(raw,['document','revision'])||typeof raw.document!=='string'||!positive(raw.revision))invalid();let documents;try{documents=JSON.parse(raw.document)}catch{invalid()}if(!exact(documents,['home','about','terms','privacy'])||!Object.values(documents).every(x=>typeof x==='string'))invalid();return Object.freeze({revision:raw.revision,documents:Object.freeze({...documents})})},{preview:true}),
 listReleases:({page=1,pageSize=20,signal}={})=>{if(!positive(page)||![20,50,100].includes(pageSize))requestError();return run({method:'GET',path:`/admin/v2/public-content/releases?page=${page}&page_size=${pageSize}`,signal},200,raw=>{if(!exact(raw,['items','page','page_size','total'])||!Array.isArray(raw.items)||!positive(raw.page)||![20,50,100].includes(raw.page_size)||!Number.isSafeInteger(raw.total)||raw.total<0)invalid();return Object.freeze({items:Object.freeze(raw.items.map(release)),page:raw.page,pageSize:raw.page_size,total:raw.total})})},
 getRelease:(id,o={})=>run({method:'GET',path:`/admin/v2/public-content/releases/${guid(id)}`,signal:o.signal},200,raw=>{if(!exact(raw,['release','content']))invalid();return Object.freeze({release:release(raw.release),content:draft(raw.content)})}),
 issuePublishVerification:(rev,password,priceReleaseGuid,o={})=>verify('public_content.publish',{price_release_guid:String(priceReleaseGuid),expected_revision:revision(rev)},password,(guid(priceReleaseGuid),o)),
 publish:(rev,priceReleaseGuid,o)=>action('/admin/v2/public-content/publish',{expected_revision:revision(rev),price_release_guid:String(priceReleaseGuid)},o),
 issueRestoreVerification:(id,rev,password,o={})=>verify('public_content.restore',{release_guid:String(id),expected_revision:revision(rev)},password,(guid(id),o)),
 restore:(id,rev,o)=>action(`/admin/v2/public-content/releases/${guid(id)}/restore`,{expected_revision:revision(rev)},o),
})}
export const publicContentAdminApi=createPublicContentAdminApi()
export function createIdempotencyKey(cryptoImpl=globalThis.crypto){if(typeof cryptoImpl?.getRandomValues!=='function')throw new Error('secure_random_unavailable');const b=new Uint8Array(32);cryptoImpl.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return'ik_'+btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
