const GUID=/^[1-9]\d{0,18}$/,MAX_GUID='9223372036854775807',DECIMAL=/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/,CODE=/^[a-z][a-z0-9_-]{0,63}$/
const OPAQUE=/^(?:av|ik)_[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/,RFC3339=/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z$/
const ADMIN_KEYS=['guid','model_key','upstream_model_id','display_name','provider','capabilities','context_window','input_price_usd_per_million_tokens','output_price_usd_per_million_tokens','status','revision','last_upstream_check_at','public_display_group','endpoint_types','public_restrictions','price_source','price_reviewer','price_effective_at']
const RELEASE_KEYS=['guid','version','reason','source_revision','created_at']
const VISIBLE_REQUIRED=['model_key','display_name','provider','capabilities','context_window','price_visibility','release_version','pricing_type','endpoint_types','updated_at']
const VISIBLE_ALLOWED=[...VISIBLE_REQUIRED,'input_price_usd_per_million_tokens','output_price_usd_per_million_tokens','public_display_group','public_restrictions','price_source','price_reviewer','effective_at']
const exact=(v,k)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===k.length&&k.every(x=>Object.hasOwn(v,x))
const positive=v=>Number.isSafeInteger(v)&&v>=1
const guid=v=>typeof v==='string'&&GUID.test(v)&&(v.length<MAX_GUID.length||v.length===MAX_GUID.length&&v<=MAX_GUID)
const list=(v,p)=>Array.isArray(v)&&new Set(v).size===v.length&&v.every(p)
const text=(v,max=255)=>typeof v==='string'&&v===v.trim()&&v.length>0&&[...v].length<=max&&!/[\p{Cc}\p{Cf}\uD800-\uDFFF]/u.test(v)
const code=v=>typeof v==='string'&&CODE.test(v)
const decimal=v=>typeof v==='string'&&DECIMAL.test(v)
const header=(h,n)=>{const v=typeof h?.get==='function'?h.get(n):h?.[n]??h?.[n.toLowerCase()];return typeof v==='string'?v:null}
const invalidRequest=()=>{throw new Error('invalid_public_pricing_admin_request')}
class InvalidResponse extends Error{constructor(){super('invalid_public_pricing_admin_response')}}
const invalid=()=>{throw new InvalidResponse()}
function metadata(result,status){if(!exact(result,['data','status','headers'])||result.status!==status||header(result.headers,'Cache-Control')!=='no-store'||!header(result.headers,'X-Request-ID')?.trim())invalid();return result.data}
function validGuid(v){if(!guid(v))invalidRequest();return encodeURIComponent(v)}
function revision(v){if(!positive(v))invalidRequest();return v}
function opaque(v,prefix){if(typeof v!=='string'||!OPAQUE.test(v)||!v.startsWith(prefix))invalidRequest();return v}
function adminModel(raw){if(!exact(raw,ADMIN_KEYS)||!guid(raw.guid)||!text(raw.model_key,128)||!text(raw.upstream_model_id)||!text(raw.display_name,128)||!text(raw.provider,128)||!list(raw.capabilities,code)||!positive(raw.context_window)||!['draft','active','inactive'].includes(raw.status)||!positive(raw.revision)||!(raw.last_upstream_check_at===null||positive(raw.last_upstream_check_at))||!code(raw.public_display_group)||!list(raw.endpoint_types,code)||!list(raw.public_restrictions,code)||typeof raw.price_source!=='string'||typeof raw.price_reviewer!=='string'||!(raw.price_effective_at===null||positive(raw.price_effective_at)))invalid();for(const k of ['input_price_usd_per_million_tokens','output_price_usd_per_million_tokens'])if(!(raw[k]===null||decimal(raw[k])))invalid();return Object.freeze({...raw,capabilities:Object.freeze([...raw.capabilities]),endpoint_types:Object.freeze([...raw.endpoint_types]),public_restrictions:Object.freeze([...raw.public_restrictions])})}
function release(raw){if(!exact(raw,RELEASE_KEYS)||!guid(raw.guid)||!positive(raw.version)||!['root_publish','upstream_safety','restore'].includes(raw.reason)||!positive(raw.source_revision)||typeof raw.created_at!=='string'||!RFC3339.test(raw.created_at)||Number.isNaN(Date.parse(raw.created_at)))invalid();return Object.freeze({guid:raw.guid,version:raw.version,reason:raw.reason,sourceRevision:raw.source_revision,createdAt:raw.created_at,systemGenerated:raw.reason==='upstream_safety'})}
function visible(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!VISIBLE_ALLOWED.includes(k))||VISIBLE_REQUIRED.some(k=>!Object.hasOwn(raw,k))||!text(raw.model_key,128)||!text(raw.display_name,128)||!text(raw.provider,128)||!list(raw.capabilities,code)||!positive(raw.context_window)||raw.price_visibility!=='visible'||!positive(raw.release_version)||raw.pricing_type!=='token'||!list(raw.endpoint_types,code)||!RFC3339.test(raw.updated_at))invalid();for(const k of ['input_price_usd_per_million_tokens','output_price_usd_per_million_tokens'])if(Object.hasOwn(raw,k)&&!decimal(raw[k]))invalid();for(const k of ['public_display_group','price_source','price_reviewer'])if(Object.hasOwn(raw,k)&&typeof raw[k]!=='string')invalid();if(Object.hasOwn(raw,'public_restrictions')&&!list(raw.public_restrictions,code))invalid();if(Object.hasOwn(raw,'effective_at')&&!RFC3339.test(raw.effective_at))invalid();return Object.freeze({modelKey:raw.model_key,displayName:raw.display_name,provider:raw.provider,capabilities:Object.freeze([...raw.capabilities]),contextWindow:raw.context_window,inputPriceUsdPerMillionTokens:raw.input_price_usd_per_million_tokens??null,outputPriceUsdPerMillionTokens:raw.output_price_usd_per_million_tokens??null,priceVisibility:raw.price_visibility,releaseVersion:raw.release_version,pricingType:raw.pricing_type,publicDisplayGroup:raw.public_display_group??'',endpointTypes:Object.freeze([...raw.endpoint_types]),publicRestrictions:Object.freeze([...(raw.public_restrictions??[])]),priceSource:raw.price_source??'',priceReviewer:raw.price_reviewer??'',effectiveAt:raw.effective_at??null,updatedAt:raw.updated_at})}
export class PublicPricingAdminError extends Error{constructor(code,status=null,requestId=null){super(code==='revision_conflict'?'发布修订已变化，请刷新比较后重试':'请求未完成，请稍后重试');this.name='PublicPricingAdminError';Object.defineProperties(this,{code:{value:code,enumerable:true},status:{value:status,enumerable:true},requestId:{value:requestId,enumerable:true}})}}
function mapError(e){if(e?.name==='AbortError')return e;const status=Number.isInteger(e?.response?.status)?e.response.status:null,raw=e?.response?.data,rid=header(e?.response?.headers,'X-Request-ID'),expected=({400:'invalid_request',401:'authentication_required',403:'root_role_required',404:'not_found',409:'conflict',410:'gone',422:'validation_failed',503:'unavailable'})[status];const valid=expected&&header(e?.response?.headers,'Cache-Control')==='no-store'&&rid?.trim()&&exact(raw,['error'])&&exact(raw.error,['code','message','request_id'])&&raw.error.code===expected&&raw.error.request_id===rid&&typeof raw.error.message==='string';if(!valid)return new PublicPricingAdminError(status?'request_failed':'network_error',status);return new PublicPricingAdminError(status===409?'revision_conflict':status===403?'root_required':expected,status,rid)}
const VERIFICATION_CODES=new Map([[400,new Set(['invalid_admin_action_request'])],[403,new Set(['action_verification_rejected'])],[409,new Set(['action_verification_conflict'])],[422,new Set(['action_inactive'])],[429,new Set(['action_rate_limited'])],[503,new Set(['action_dependency_unavailable'])]])
function mapVerificationError(e){if(e?.name==='AbortError')return e;const status=Number.isInteger(e?.response?.status)?e.response.status:null,raw=e?.response?.data,rid=header(e?.response?.headers,'X-Request-ID'),payload=raw?.error;const keys=payload?.operation_ref===undefined?['code','message','type','request_id']:['code','message','type','request_id','operation_ref'];const valid=header(e?.response?.headers,'Cache-Control')==='no-store'&&rid?.trim()&&exact(raw,['error'])&&exact(payload,keys)&&payload.type==='admin_action_error'&&payload.message==='请求无法完成'&&payload.request_id===rid&&VERIFICATION_CODES.get(status)?.has(payload.code)&&payload.operation_ref===undefined;if(!valid)return new PublicPricingAdminError(status?'request_failed':'network_error',status);return new PublicPricingAdminError(payload.code,status,rid)}
export function createPublicPricingAdminProductionRequest({get,mutation,actionPost}={}){return async args=>{if(args.method==='GET')return get(args.path,{signal:args.signal});if(args.method==='PUT')return mutation({method:'PUT',path:args.path,body:args.body,signal:args.signal});if(args.method==='POST')return actionPost(args.path,args.body,{headers:args.headers,signal:args.signal});invalidRequest()}}
async function productionRequest(args){const {authenticatedFetch,adminActionPost,default:request}=await import('./request.js'),base=import.meta.env?.VITE_API_BASE??'';const adapter=createPublicPricingAdminProductionRequest({get:async(path,options)=>{const response=await authenticatedFetch(base+path,{method:'GET',signal:options.signal});let data=null;try{data=await response.json()}catch{}const out={data,status:response.status,headers:response.headers};if(!response.ok)throw{response:out};return out},mutation:async({method,path,body,signal})=>{const response=await request.request({method,url:path,data:body,signal});return{data:response.data,status:response.status,headers:response.headers}},actionPost:adminActionPost});return adapter(args)}
export function createPublicPricingAdminApi({request=productionRequest}={}){const run=async(args,status,mapper)=>{try{return mapper(metadata(await request(args),status))}catch(e){if(e instanceof InvalidResponse)throw e;throw mapError(e)}};const verify=async(action,intent,password,options={})=>{if(typeof password!=='string'||!password||/[\u0000-\u001f\u007f]/.test(password))invalidRequest();try{const raw=metadata(await request({method:'POST',path:'/admin/v2/action-verifications',body:{action,intent,current_password:password},signal:options.signal}),201);if(!exact(raw,['ticket','expires_at'])||typeof raw.ticket!=='string'||!OPAQUE.test(raw.ticket)||!raw.ticket.startsWith('av_')||!positive(raw.expires_at))invalid();return Object.freeze({ticket:raw.ticket,expiresAt:raw.expires_at})}catch(e){if(e instanceof InvalidResponse)throw e;throw mapVerificationError(e)}};const action=(path,rev,options)=>{if(!options||Object.keys(options).some(k=>!['ticket','idempotencyKey','signal'].includes(k)))invalidRequest();return run({method:'POST',path,body:{expected_revision:revision(rev)},headers:{'Idempotency-Key':opaque(options.idempotencyKey,'ik_'),'X-Action-Ticket':opaque(options.ticket,'av_')},signal:options.signal},201,release)};return Object.freeze({
 getDraft:(o={})=>run({method:'GET',path:'/admin/v2/public-pricing/draft',signal:o.signal},200,raw=>{if(!exact(raw,['revision','models','currency','unit'])||!positive(raw.revision)||raw.currency!=='USD'||raw.unit!=='million_tokens'||!Array.isArray(raw.models))invalid();return Object.freeze({revision:raw.revision,models:Object.freeze(raw.models.map(adminModel)),currency:'USD',unit:'million_tokens'})}),
 saveDraft:(rev,models,o={})=>{if(!Array.isArray(models))invalidRequest();const safeModels=models.map(adminModel);return run({method:'PUT',path:'/admin/v2/public-pricing/draft',body:{expected_revision:revision(rev),models:safeModels},signal:o.signal},200,raw=>{if(!exact(raw,['revision','models','currency','unit'])||!positive(raw.revision)||raw.currency!=='USD'||raw.unit!=='million_tokens'||!Array.isArray(raw.models))invalid();return Object.freeze({revision:raw.revision,models:Object.freeze(raw.models.map(adminModel)),currency:'USD',unit:'million_tokens'})})},
 validate:(rev,o={})=>run({method:'POST',path:'/admin/v2/public-pricing/validate',body:{expected_revision:revision(rev)},signal:o.signal},200,raw=>{if(!exact(raw,['valid','issues'])||typeof raw.valid!=='boolean'||!Array.isArray(raw.issues))invalid();const issues=raw.issues.map(x=>{if(!exact(x,['field','code'])||!text(x.field,255)||!code(x.code))invalid();return Object.freeze({field:x.field,code:x.code})});return Object.freeze({valid:raw.valid,issues:Object.freeze(issues)})}),
 listReleases:({page=1,pageSize=20,signal}={})=>{if(!positive(page)||![20,50,100].includes(pageSize))invalidRequest();return run({method:'GET',path:`/admin/v2/public-pricing/releases?page=${page}&page_size=${pageSize}`,signal},200,raw=>{if(!exact(raw,['items','page','page_size','total'])||!Array.isArray(raw.items)||!positive(raw.page)||![20,50,100].includes(raw.page_size)||!Number.isSafeInteger(raw.total)||raw.total<0)invalid();return Object.freeze({items:Object.freeze(raw.items.map(release)),page:raw.page,pageSize:raw.page_size,total:raw.total})})},
 getRelease:(id,o={})=>run({method:'GET',path:`/admin/v2/public-pricing/releases/${validGuid(id)}`,signal:o.signal},200,raw=>{if(!exact(raw,['release','items'])||!Array.isArray(raw.items))invalid();return Object.freeze({release:release(raw.release),items:Object.freeze(raw.items.map(visible))})}),
 issuePublishVerification:(rev,password,o={})=>verify('public_pricing.publish',{expected_revision:revision(rev)},password,o),
 publish:(rev,o)=>action('/admin/v2/public-pricing/publish',rev,o),
 issueRestoreVerification:(id,rev,password,o={})=>{validGuid(String(id));return verify('public_pricing.restore',{release_guid:String(id),expected_revision:revision(rev)},password,o)},
 restore:(id,rev,o)=>action(`/admin/v2/public-pricing/releases/${validGuid(id)}/restore`,rev,o),
})}
export const publicPricingAdminApi=createPublicPricingAdminApi()

const safeError=e=>Object.freeze({code:typeof e?.code==='string'&&/^[a-z_]{1,64}$/.test(e.code)?e.code:'request_failed',requestId:typeof e?.requestId==='string'&&/^[A-Za-z0-9._:-]{1,128}$/.test(e.requestId)?e.requestId:null})
export function createIdempotencyKey(cryptoImpl=globalThis.crypto){if(typeof cryptoImpl?.getRandomValues!=='function')throw new Error('secure_random_unavailable');const bytes=new Uint8Array(32);cryptoImpl.getRandomValues(bytes);let raw='';for(const x of bytes)raw+=String.fromCharCode(x);return 'ik_'+btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export function createPricingValidationCoordinator({api=publicPricingAdminApi,state={}}={}){
 Object.assign(state,{draftRevision:null,result:null,loading:false,error:null,...state});let generation=0,controller=null
 return{state,setRevision(value){generation++;controller?.abort();controller=null;state.draftRevision=positive(value)?value:null;state.result=null;state.loading=false;state.error=null},async validate(){const revision=state.draftRevision;if(!positive(revision))return null;const own=++generation;controller?.abort();controller=new AbortController();state.loading=true;state.error=null;try{const result=await api.validate(revision,{signal:controller.signal});if(own!==generation||state.draftRevision!==revision)return null;state.result=Object.freeze({...result,validatedRevision:revision});return state.result}catch(e){if(own===generation&&e?.name!=='AbortError')state.error=safeError(e);return null}finally{if(own===generation){state.loading=false;controller=null}}},isCurrent(revision){return positive(revision)&&state.result?.valid===true&&state.result.validatedRevision===revision},cancel(){generation++;controller?.abort();controller=null;state.loading=false;state.result=null;state.error=null}}
}
export function createPricingPublicationCoordinator({api=publicPricingAdminApi,state={},generateKey=createIdempotencyKey}={}){
 Object.assign(state,{busy:false,error:null,conflict:false,pendingRecovery:false,pendingOperation:null,reconcileRequired:false,...state})
 let generation=0,pending=null,attempt=null,controller=null
 const clearAttempt=()=>{attempt=null;state.pendingRecovery=false;state.pendingOperation=null}
 const rejectDrift=()=>{clearAttempt();state.conflict=true;state.reconcileRequired=true;state.error=Object.freeze({code:'revision_conflict',requestId:null});return Promise.resolve(null)}
 const start=(kind,releaseGuid,input)=>{
  if(pending)return pending
  const currentRevision=state.draft?.revision
  if(!positive(currentRevision))return Promise.resolve(null)
  if(attempt&&(attempt.kind!==kind||attempt.releaseGuid!==releaseGuid))return Promise.resolve(null)
  if(attempt&&attempt.expectedRevision!==currentRevision)return rejectDrift()
  const own=++generation;controller=new AbortController();state.busy=true;state.error=null;state.conflict=false;state.reconcileRequired=false
  let password=input?.currentPassword
  try{if(input&&typeof input==='object')input.currentPassword=null}catch{}
  if(!attempt){try{attempt=Object.freeze({kind,releaseGuid,expectedRevision:currentRevision,key:generateKey()})}catch(e){password=null;state.busy=false;state.error=safeError(e);return Promise.resolve(null)}}
  const descriptor=attempt
  pending=(async()=>{try{
   const issued=kind==='publish'?await api.issuePublishVerification(descriptor.expectedRevision,password,{signal:controller.signal}):await api.issueRestoreVerification(descriptor.releaseGuid,descriptor.expectedRevision,password,{signal:controller.signal})
   password=null;if(own!==generation)return null
   const out=kind==='publish'?await api.publish(descriptor.expectedRevision,{ticket:issued.ticket,idempotencyKey:descriptor.key,signal:controller.signal}):await api.restore(descriptor.releaseGuid,descriptor.expectedRevision,{ticket:issued.ticket,idempotencyKey:descriptor.key,signal:controller.signal})
   if(own!==generation)return null
   clearAttempt();state.lastRelease=out;return out
  }catch(e){password=null;if(own!==generation||e?.name==='AbortError')return null;state.error=safeError(e);state.conflict=e?.code==='revision_conflict';state.reconcileRequired=state.conflict;state.pendingRecovery=e?.code==='network_error';state.pendingOperation=state.pendingRecovery?descriptor.kind:null;if(!state.pendingRecovery)attempt=null;return null
  }finally{password=null;if(own===generation){state.busy=false;pending=null}}})()
  return pending
 }
 return{state,publish:input=>start('publish',undefined,input),restore:(releaseGuid,input)=>start('restore',String(releaseGuid),input),cancel(){generation++;controller?.abort();controller=null;pending=null;attempt=null;state.busy=false;state.pendingRecovery=false;state.pendingOperation=null;state.error=null},clearAttempt(){clearAttempt();state.reconcileRequired=true}}
}
