const GUID=/^[1-9]\d{0,18}$/
const MAX_INT64='9223372036854775807'
const DECIMAL=/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/
const MODEL_KEY=/^[a-z][a-z0-9-]{0,127}$/
const CODE=/^[a-z][a-z0-9_-]{0,63}$/
const TICKET=/^av_[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/
const UNSAFE=/[\p{Cc}\p{Cf}]/u
const LONE_SURROGATE=/(?:[\uD800-\uDBFF](?![\uDC00-\uDFFF]))|(?:(?<![\uD800-\uDBFF])[\uDC00-\uDFFF])/
const MODEL_KEYS=['guid','model_key','upstream_model_id','display_name','provider','capabilities','context_window','input_price_usd_per_million_tokens','output_price_usd_per_million_tokens','status','revision','last_upstream_check_at','public_display_group','endpoint_types','public_restrictions','price_source','price_reviewer','price_effective_at']
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k))
const positive=v=>Number.isSafeInteger(v)&&v>=1
class InvalidPublicModelAdminResponse extends Error{constructor(){super('invalid_public_model_admin_response')}}
const invalid=()=>{throw new InvalidPublicModelAdminResponse()}
const validGuid=v=>typeof v==='string'&&GUID.test(v)&&(v.length<MAX_INT64.length||v.length===MAX_INT64.length&&v<=MAX_INT64)
const validText=(v,max,optional=false)=>typeof v==='string'&&(optional||v!=='')&&v===v.trim()&&[...v].length<=max&&!UNSAFE.test(v)&&!LONE_SURROGATE.test(v)
const validCodeList=v=>Array.isArray(v)&&v.length<=32&&new Set(v).size===v.length&&v.every(x=>typeof x==='string'&&CODE.test(x))
const validModelKey=v=>typeof v==='string'&&MODEL_KEY.test(v)&&!v.endsWith('-')&&!v.includes('--')
const validUpstream=v=>validText(v,255)&&v.split('/').every(s=>s&&s!=='.'&&s!=='..'&&!/[\\?#%\s]/u.test(s)&&!UNSAFE.test(s))
const validUpstreamList=v=>Array.isArray(v)&&new Set(v).size===v.length&&v.every(validUpstream)
function header(headers,name){const v=typeof headers?.get==='function'?headers.get(name):headers?.[name]??headers?.[name.toLowerCase()];return typeof v==='string'?v:null}
function metadata(result,status){if(!exact(result,['data','status','headers'])||result.status!==status||header(result.headers,'Cache-Control')!=='no-store'||!header(result.headers,'X-Request-ID')?.trim())invalid();return result.data}
function model(raw){
  if(!exact(raw,MODEL_KEYS)||!validGuid(raw.guid)||!validModelKey(raw.model_key)||!validUpstream(raw.upstream_model_id)||!validText(raw.display_name,128)||!validText(raw.provider,128)||!validCodeList(raw.capabilities)||!Number.isSafeInteger(raw.context_window)||raw.context_window<1||!['draft','active','inactive'].includes(raw.status)||!positive(raw.revision)||!(raw.last_upstream_check_at===null||positive(raw.last_upstream_check_at))||!validCodeList(raw.endpoint_types)||!validCodeList(raw.public_restrictions)||!(raw.public_display_group===''||CODE.test(raw.public_display_group))||!validText(raw.price_source,255,true)||!validText(raw.price_reviewer,128,true)||!(raw.price_effective_at===null||positive(raw.price_effective_at)))invalid()
  for(const key of ['input_price_usd_per_million_tokens','output_price_usd_per_million_tokens'])if(!(raw[key]===null||typeof raw[key]==='string'&&DECIMAL.test(raw[key])))invalid()
  if((raw.input_price_usd_per_million_tokens!==null||raw.output_price_usd_per_million_tokens!==null)&&(!raw.price_source||!raw.price_reviewer||raw.price_effective_at===null))invalid()
  return Object.freeze({guid:raw.guid,modelKey:raw.model_key,upstreamModelId:raw.upstream_model_id,displayName:raw.display_name,provider:raw.provider,capabilities:Object.freeze([...raw.capabilities]),contextWindow:raw.context_window,inputPriceUsdPerMillionTokens:raw.input_price_usd_per_million_tokens,outputPriceUsdPerMillionTokens:raw.output_price_usd_per_million_tokens,status:raw.status,revision:raw.revision,lastUpstreamCheckAt:raw.last_upstream_check_at,publicDisplayGroup:raw.public_display_group,endpointTypes:Object.freeze([...raw.endpoint_types]),publicRestrictions:Object.freeze([...raw.public_restrictions]),priceSource:raw.price_source,priceReviewer:raw.price_reviewer,priceEffectiveAt:raw.price_effective_at})
}
function guid(value){if(!validGuid(value))throw new Error('invalid_public_model_admin_request');return encodeURIComponent(value)}
function revision(value){if(!positive(value))throw new Error('invalid_public_model_admin_request');return value}
function reason(value){if(!validText(value,128))throw new Error('invalid_public_model_admin_request');return value}
export class PublicModelAdminError extends Error{constructor(code,status=null,requestId=null){super(code==='revision_conflict'?'请求失败，请刷新后重试':'请求失败，请稍后重试');this.name='PublicModelAdminError';Object.defineProperties(this,{code:{value:code,enumerable:true},status:{value:status,enumerable:true},requestId:{value:requestId,enumerable:true}})}}
function mapError(error){if(error?.name==='AbortError')return error;const response=error?.response,status=Number.isInteger(response?.status)?response.status:null,raw=response?.data,requestID=header(response?.headers,'X-Request-ID');const expected=({400:'invalid_request',401:'authentication_required',403:'root_role_required',404:'not_found',409:'conflict',410:'gone',422:'validation_failed',503:'unavailable'})[status];const valid=expected&&header(response?.headers,'Cache-Control')==='no-store'&&requestID?.trim()&&exact(raw,['error'])&&exact(raw.error,['code','message','request_id'])&&raw.error.code===expected&&typeof raw.error.message==='string'&&raw.error.request_id===requestID;if(!valid)return new PublicModelAdminError(status?'request_failed':'network_error',status);return new PublicModelAdminError(status===409?'revision_conflict':({401:'authentication_required',403:'root_required',404:'not_found',410:'gone',503:'unavailable'})[status]??expected,status,requestID)}
export function publicModelAdminListResource(filters={}){const allowed=new Set(['search','status','upstreamState','page','pageSize']);if(!filters||typeof filters!=='object'||Object.keys(filters).some(k=>!allowed.has(k)))throw new Error('invalid_public_model_admin_query');const p=new URLSearchParams();if(filters.search!==undefined&&filters.search!==''){if(!validText(filters.search,128))throw new Error('invalid_public_model_admin_query');p.set('search',filters.search)}if(filters.status!==undefined){if(!['draft','active','inactive'].includes(filters.status))throw new Error('invalid_public_model_admin_query');p.set('status',filters.status)}if(filters.upstreamState!==undefined){if(!['present','missing'].includes(filters.upstreamState))throw new Error('invalid_public_model_admin_query');p.set('upstream_state',filters.upstreamState)}if(filters.page!==undefined){if(!positive(filters.page))throw new Error('invalid_public_model_admin_query');p.set('page',String(filters.page))}if(filters.pageSize!==undefined){if(![20,50,100].includes(filters.pageSize))throw new Error('invalid_public_model_admin_query');p.set('page_size',String(filters.pageSize))}const q=p.toString();return '/admin/v2/public-models'+(q?'?'+q:'')}
async function productionRequest({method,path,body,headers={},signal}){const {authenticatedFetch,getAuthToken}=await import('./request.js');const baseURL=import.meta.env?.VITE_API_BASE??'',url=`${baseURL}${path}`;const requestHeaders={...headers};if(body!==undefined)requestHeaders['Content-Type']='application/json';const token=getAuthToken();if(token)requestHeaders.Authorization=`Bearer ${token}`;const response=method==='GET'?await authenticatedFetch(url,{method,headers:requestHeaders,signal}):await fetch(url,{method,headers:requestHeaders,body:body===undefined?undefined:JSON.stringify(body),credentials:'include',signal});let data=null;if(response.status!==204){try{data=await response.json()}catch{data=null}}const result={data,status:response.status,headers:response.headers};if(!response.ok)throw {response:result};return result}
export function createPublicModelAdminApi({request=productionRequest}={}){
  const run=async(args,status,mapper)=>{try{return mapper(metadata(await request(args),status))}catch(e){if(e instanceof InvalidPublicModelAdminResponse)throw e;throw mapError(e)}}
  return Object.freeze({
    list:(filters={},options={})=>run({method:'GET',path:publicModelAdminListResource(filters),signal:options.signal},200,raw=>{if(!exact(raw,['items','page','page_size','total'])||!Array.isArray(raw.items)||!positive(raw.page)||![20,50,100].includes(raw.page_size)||!Number.isSafeInteger(raw.total)||raw.total<0)invalid();return Object.freeze({items:Object.freeze(raw.items.map(model)),page:raw.page,pageSize:raw.page_size,total:raw.total})}),
    get:(id,options={})=>run({method:'GET',path:`/admin/v2/public-models/${guid(id)}`,signal:options.signal},200,model),
    create:(form,{recentlyObservedIds,signal}={})=>run({method:'POST',path:'/admin/v2/public-models',body:normalizePublicModelCreateForm(form,{recentlyObservedIds}),signal},201,model),
    update:(id,form,{current,signal}={})=>run({method:'PATCH',path:`/admin/v2/public-models/${guid(id)}`,body:normalizePublicModelUpdateForm(form,{current}),signal},200,model),
    activate:(id,expectedRevision,options={})=>run({method:'POST',path:`/admin/v2/public-models/${guid(id)}/activate`,body:{expected_revision:revision(expectedRevision)},signal:options.signal},200,model),
    deactivate:(id,expectedRevision,why,options={})=>run({method:'POST',path:`/admin/v2/public-models/${guid(id)}/deactivate`,body:{expected_revision:revision(expectedRevision),reason:reason(why)},signal:options.signal},200,model),
    getMissing:(options={})=>run({method:'GET',path:'/admin/v2/public-models/missing',signal:options.signal},200,raw=>{if(!exact(raw,['observed_without_configuration','configured_missing_upstream'])||!validUpstreamList(raw.observed_without_configuration)||!Array.isArray(raw.configured_missing_upstream))invalid();return Object.freeze({observedWithoutConfiguration:Object.freeze([...raw.observed_without_configuration]),configuredMissingUpstream:Object.freeze(raw.configured_missing_upstream.map(model))})}),
    sync:(options={})=>run({method:'POST',path:'/admin/v2/public-models/sync',signal:options.signal},202,raw=>{if(!exact(raw,['accepted'])||raw.accepted!==true)invalid();return Object.freeze({accepted:true})}),
    issueDeleteVerification:({guid:id,expectedRevision,currentPassword,reason:why},options={})=>{if(typeof currentPassword!=='string'||!currentPassword||UNSAFE.test(currentPassword))throw new Error('invalid_public_model_admin_request');const intent={target_guid:String(id),expected_revision:revision(expectedRevision),reason:reason(why)};guid(String(id));return run({method:'POST',path:'/admin/v2/action-verifications',body:{action:'public_models.delete',intent,current_password:currentPassword},signal:options.signal},201,raw=>{if(!exact(raw,['ticket','expires_at'])||!TICKET.test(raw.ticket)||!positive(raw.expires_at))invalid();return Object.freeze({ticket:raw.ticket,expiresAt:raw.expires_at})})},
    deleteModel:(id,{expectedRevision,reason:why,ticket},options={})=>{if(typeof ticket!=='string'||!TICKET.test(ticket))throw new Error('invalid_public_model_admin_request');return run({method:'DELETE',path:`/admin/v2/public-models/${guid(id)}`,body:{expected_revision:revision(expectedRevision),reason:reason(why)},headers:{'X-Action-Ticket':ticket},signal:options.signal},204,raw=>{if(raw!==null&&raw!==undefined&&raw!=='')invalid();return true})},
  })
}
export const publicModelAdminApi=createPublicModelAdminApi()
import {normalizePublicModelCreateForm,normalizePublicModelUpdateForm} from '../utils/public-model-form.js'
