const GUID=/^[1-9]\d{0,18}$/,MAX_GUID='9223372036854775807',OPAQUE=/^(?:av|ik)_[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/,CODE=/^[a-z][a-z0-9_-]{0,63}$/,RFC3339=/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z$/
const DRAFT_KEYS=['revision','home','about','terms','privacy','legal_reviewed'],RELEASE_KEYS=['guid','version','reason','source_revision','created_at']
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.getPrototypeOf(v)!==null&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k))
const positive=v=>Number.isSafeInteger(v)&&v>=1
const header=(h,n)=>{const v=typeof h?.get==='function'?h.get(n):h?.[n]??h?.[n.toLowerCase()];return typeof v==='string'?v:null}
const validGuid=v=>typeof v==='string'&&GUID.test(v)&&(v.length<MAX_GUID.length||v.length===MAX_GUID.length&&v<=MAX_GUID)
const requestError=()=>{throw new Error('invalid_public_content_admin_request')}
class InvalidResponse extends Error{constructor(){super('invalid_public_content_admin_response')}}
const invalid=()=>{throw new InvalidResponse()}
function metadata(result,status,{preview=false}={}){if(!exact(result,['data','status','headers'])||result.status!==status||header(result.headers,'Cache-Control')!=='no-store'||!header(result.headers,'X-Request-ID')?.trim()||(preview&&header(result.headers,'X-Robots-Tag')!=='noindex, nofollow'))invalid();return result.data}
function revision(v){if(!positive(v))requestError();return v}
function guid(v){v=String(v);if(!validGuid(v))requestError();return encodeURIComponent(v)}
function opaque(v,prefix){if(typeof v!=='string'||!OPAQUE.test(v)||!v.startsWith(prefix))requestError();return v}
function cleanText(v,max=262144){return typeof v==='string'&&v.length<=max&&!/[\u0000]/.test(v)}
function draft(raw){if(!exact(raw,DRAFT_KEYS)||!positive(raw.revision)||!cleanText(raw.home)||!cleanText(raw.about)||!cleanText(raw.terms)||!cleanText(raw.privacy)||typeof raw.legal_reviewed!=='boolean')invalid();return Object.freeze({revision:raw.revision,home:raw.home,about:raw.about,terms:raw.terms,privacy:raw.privacy,legalReviewed:raw.legal_reviewed})}
function utc(v){if(typeof v!=='string'||!RFC3339.test(v))return false;const ms=Date.parse(v);return Number.isFinite(ms)&&new Date(ms).toISOString().slice(0,19)===v.slice(0,19)}
function release(raw){if(!exact(raw,RELEASE_KEYS)||!validGuid(raw.guid)||!positive(raw.version)||!['root_publish','restore'].includes(raw.reason)||!positive(raw.source_revision)||!utc(raw.created_at))invalid();return Object.freeze({guid:raw.guid,version:raw.version,reason:raw.reason,sourceRevision:raw.source_revision,createdAt:raw.created_at})}
function mapIssue(raw){if(!exact(raw,['field','code'])||typeof raw.field!=='string'||!raw.field||!CODE.test(raw.code))invalid();return Object.freeze({field:raw.field,code:raw.code})}
export class PublicContentAdminError extends Error{constructor(code,status=null,requestId=null){super(code);this.name='PublicContentAdminError';Object.assign(this,{code,status,requestId})}}
function mapError(e){if(e?.name==='AbortError')return e;const status=Number.isInteger(e?.response?.status)?e.response.status:null,raw=e?.response?.data,rid=header(e?.response?.headers,'X-Request-ID'),expected=({400:'invalid_request',401:'authentication_required',403:'root_role_required',404:'not_found',409:'conflict',410:'gone',422:'validation_failed',503:'unavailable'})[status];const valid=expected&&header(e?.response?.headers,'Cache-Control')==='no-store'&&rid?.trim()&&exact(raw,['error'])&&exact(raw.error,['code','message','request_id'])&&raw.error.code===expected&&raw.error.request_id===rid&&typeof raw.error.message==='string';if(!valid)return new PublicContentAdminError(status?'request_failed':'network_error',status);return new PublicContentAdminError(status===409?'revision_conflict':status===403?'root_required':expected,status,rid)}
const VERIFY=new Map([[400,new Set(['invalid_admin_action_request'])],[403,new Set(['action_verification_rejected'])],[409,new Set(['action_verification_conflict'])],[422,new Set(['action_inactive'])],[429,new Set(['action_rate_limited'])],[503,new Set(['action_dependency_unavailable'])]])
function mapVerifyError(e){if(e?.name==='AbortError')return e;const status=e?.response?.status,raw=e?.response?.data,rid=header(e?.response?.headers,'X-Request-ID'),p=raw?.error;const valid=header(e?.response?.headers,'Cache-Control')==='no-store'&&rid?.trim()&&exact(raw,['error'])&&exact(p,['code','message','type','request_id'])&&p.type==='admin_action_error'&&p.request_id===rid&&VERIFY.get(status)?.has(p.code);return valid?new PublicContentAdminError(p.code,status,rid):new PublicContentAdminError(status?'request_failed':'network_error',status)}
export function createPublicContentAdminProductionRequest({get,mutation,actionPost}={}){return async a=>a.method==='GET'?get(a.path,{signal:a.signal}):a.method==='PUT'?mutation({method:'PUT',path:a.path,body:a.body,signal:a.signal}):a.method==='POST'?actionPost(a.path,a.body,{headers:a.headers,signal:a.signal}):requestError()}
async function productionRequest(a){const {authenticatedFetch,adminActionPost,default:req}=await import('./request.js'),base=import.meta.env?.VITE_API_BASE??'';return createPublicContentAdminProductionRequest({get:async(path,o)=>{const r=await authenticatedFetch(base+path,{method:'GET',signal:o.signal});let data;try{data=await r.json()}catch{}const x={data,status:r.status,headers:r.headers};if(!r.ok)throw{response:x};return x},mutation:async x=>{const r=await req.request({method:x.method,url:x.path,data:x.body,signal:x.signal});return{data:r.data,status:r.status,headers:r.headers}},actionPost:adminActionPost})(a)}
export function createPublicContentAdminApi({request=productionRequest}={}){const run=async(a,status,mapper,opts)=>{try{return mapper(metadata(await request(a),status,opts))}catch(e){if(e instanceof InvalidResponse)throw e;throw mapError(e)}};const verify=async(action,intent,password,o={})=>{if(typeof password!=='string'||!password||/[\u0000-\u001f\u007f]/.test(password))requestError();try{const raw=metadata(await request({method:'POST',path:'/admin/v2/action-verifications',body:{action,intent,current_password:password},signal:o.signal}),201);if(!exact(raw,['ticket','expires_at'])||!OPAQUE.test(raw.ticket)||!raw.ticket.startsWith('av_')||!positive(raw.expires_at))invalid();return Object.freeze({ticket:raw.ticket,expiresAt:raw.expires_at})}catch(e){if(e instanceof InvalidResponse)throw e;throw mapVerifyError(e)}};const action=(path,body,o)=>{if(!o||Object.keys(o).some(k=>!['ticket','idempotencyKey','signal'].includes(k)))requestError();return run({method:'POST',path,body,headers:{'Idempotency-Key':opaque(o.idempotencyKey,'ik_'),'X-Action-Ticket':opaque(o.ticket,'av_')},signal:o.signal},201,release)};return Object.freeze({
 getDraft:(o={})=>run({method:'GET',path:'/admin/v2/public-content/draft',signal:o.signal},200,draft),
 saveDraft:(value,o={})=>{if(!value||Object.keys(value).some(k=>!['revision','home','about','terms','privacy','legalReviewed'].includes(k))||!positive(value.revision)||![value.home,value.about,value.terms,value.privacy].every(x=>cleanText(x))||typeof value.legalReviewed!=='boolean')requestError();return run({method:'PUT',path:'/admin/v2/public-content/draft',body:{expected_revision:value.revision,home:value.home,about:value.about,terms:value.terms,privacy:value.privacy,legal_reviewed:value.legalReviewed},signal:o.signal},200,draft)},
 validate:(rev,o={})=>run({method:'POST',path:'/admin/v2/public-content/validate',body:{expected_revision:revision(rev)},signal:o.signal},200,raw=>{if(!exact(raw,['valid','issues'])||typeof raw.valid!=='boolean'||!Array.isArray(raw.issues))invalid();return Object.freeze({valid:raw.valid,issues:Object.freeze(raw.issues.map(mapIssue))})}),
 preview:(rev,o={})=>run({method:'GET',path:`/admin/v2/public-content/preview?revision=${revision(rev)}`,signal:o.signal},200,raw=>{if(!exact(raw,['document','revision'])||typeof raw.document!=='string'||!positive(raw.revision))invalid();let documents;try{documents=JSON.parse(raw.document)}catch{invalid()}if(!exact(documents,['home','about','terms','privacy'])||!Object.values(documents).every(x=>typeof x==='string'))invalid();return Object.freeze({revision:raw.revision,documents:Object.freeze({...documents})})},{preview:true}),
 listReleases:({page=1,pageSize=20,signal}={})=>{if(!positive(page)||![20,50,100].includes(pageSize))requestError();return run({method:'GET',path:`/admin/v2/public-content/releases?page=${page}&page_size=${pageSize}`,signal},200,raw=>{if(!exact(raw,['items','page','page_size','total'])||!Array.isArray(raw.items)||!positive(raw.page)||![20,50,100].includes(raw.page_size)||!Number.isSafeInteger(raw.total)||raw.total<0)invalid();return Object.freeze({items:Object.freeze(raw.items.map(release)),page:raw.page,pageSize:raw.page_size,total:raw.total})})},
 getRelease:(id,o={})=>run({method:'GET',path:`/admin/v2/public-content/releases/${guid(id)}`,signal:o.signal},200,raw=>{if(!exact(raw,['release','content']))invalid();return Object.freeze({release:release(raw.release),content:draft(raw.content)})}),
 issuePublishVerification:(rev,password,priceReleaseGuid,o={})=>verify('public_content.publish',{price_release_guid:String(priceReleaseGuid),expected_revision:revision(rev)},password,(guid(priceReleaseGuid),o)),
 publish:(rev,priceReleaseGuid,o)=>action('/admin/v2/public-content/publish',{expected_revision:revision(rev),price_release_guid:String(priceReleaseGuid)},o),
 issueRestoreVerification:(id,rev,password,o={})=>verify('public_content.restore',{release_guid:String(id),expected_revision:revision(rev)},password,(guid(id),o)),
 restore:(id,rev,o)=>action(`/admin/v2/public-content/releases/${guid(id)}/restore`,{expected_revision:revision(rev)},o),
})}
export const publicContentAdminApi=createPublicContentAdminApi()
export function createIdempotencyKey(cryptoImpl=globalThis.crypto){if(typeof cryptoImpl?.getRandomValues!=='function')throw new Error('secure_random_unavailable');const b=new Uint8Array(32);cryptoImpl.getRandomValues(b);let s='';for(const x of b)s+=String.fromCharCode(x);return'ik_'+btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
export function canonicalContentDraft(value){if(!value||!positive(value.revision)||![value.home,value.about,value.terms,value.privacy].every(x=>cleanText(x))||typeof value.legalReviewed!=='boolean')requestError();return JSON.stringify({revision:value.revision,home:value.home,about:value.about,terms:value.terms,privacy:value.privacy,legal_reviewed:value.legalReviewed})}
export async function hashCanonicalContent(value,cryptoImpl=globalThis.crypto){if(typeof cryptoImpl?.subtle?.digest!=='function')throw new Error('secure_digest_unavailable');const bytes=new TextEncoder().encode(canonicalContentDraft(value)),digest=new Uint8Array(await cryptoImpl.subtle.digest('SHA-256',bytes));return [...digest].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function createContentValidationProof(draftValue,priceReleaseGuid,result,cryptoImpl=globalThis.crypto){const target=String(priceReleaseGuid);guid(target);if(result?.valid!==true)return null;const canonical=canonicalContentDraft(draftValue);return Object.freeze({valid:true,revision:draftValue.revision,canonical,contentHash:await hashCanonicalContent(draftValue,cryptoImpl),priceReleaseGuid:target})}
export function contentValidationProofMatches(proof,draftValue,savedCanonical,priceReleaseGuid,approvalEvidence){if(approvalEvidence?.approved!==true||typeof approvalEvidence.source!=='string'||!approvalEvidence.source)return false;let current;try{current=canonicalContentDraft(draftValue)}catch{return false}return proof?.valid===true&&proof.revision===draftValue.revision&&proof.canonical===current&&proof.canonical===savedCanonical&&proof.priceReleaseGuid===String(priceReleaseGuid)&&/^[a-f0-9]{64}$/.test(proof.contentHash)}

const MODEL_KEY=/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/
const UTC_SECONDS=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/
const utf8Bytes=value=>new TextEncoder().encode(value).length
function strictObject(value,keys){if(!value||typeof value!=='object'||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return null;const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(key=>typeof key!=='string')||Object.keys(value).length!==keys.length)return null;const output={};for(const key of keys){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor||!('value'in descriptor)||!descriptor.enumerable)return null;output[key]=descriptor.value}return output}
function strictArray(value){if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)return null;const own=Reflect.ownKeys(value);if(own.some(key=>typeof key==='symbol')||own.length!==value.length+1||!own.includes('length'))return null;const output=[];for(let index=0;index<value.length;index++){const descriptor=Object.getOwnPropertyDescriptor(value,String(index));if(!descriptor||!('value'in descriptor)||!descriptor.enumerable)return null;output.push(descriptor.value)}return output}
function structuredText(value,{maxCodepoints,maxBytes,plain=false}={}){if(typeof value!=='string'||utf8Bytes(value)>(maxBytes??262144)||[...value].length>(maxCodepoints??262144)||value.includes('\uFFFD'))return false;for(const character of value){const point=character.codePointAt(0);if((point>=0xD800&&point<=0xDFFF)||(point>=0xFDD0&&point<=0xFDEF)||(point&0xFFFF)===0xFFFE||(point&0xFFFF)===0xFFFF||/\p{Cf}/u.test(character)||(/\p{Cc}/u.test(character)&&(plain||!['\t','\n','\r'].includes(character))))return false}return !plain||(value===value.trim()&&Boolean(value))}
function structuredUTC(value){if(value===null)return true;if(typeof value!=='string'||!UTC_SECONDS.test(value))return false;const timestamp=Date.parse(value);return Number.isFinite(timestamp)&&new Date(timestamp).toISOString().replace('.000Z','Z')===value}
function structuredGuid(value){return typeof value==='string'&&validGuid(value)}
function structuredModelKey(value){return typeof value==='string'&&value.length<=128&&MODEL_KEY.test(value)}
function structuredSort(value){return Number.isSafeInteger(value)&&value>=0&&value<=1000000}
function compareGuid(left,right){const a=BigInt(left),b=BigInt(right);return a<b?-1:a>b?1:0}
function announcementOrder(left,right){return left.sort_order-right.sort_order||(left.effective_at===right.effective_at?compareGuid(left.guid,right.guid):left.effective_at===null?-1:right.effective_at===null?1:left.effective_at.localeCompare(right.effective_at))}
function faqOrder(left,right){return left.sort_order-right.sort_order||compareGuid(left.guid,right.guid)}
function canonicalStructuredValue(input){
 const root=strictObject(input,['revision','documents','home']);if(!root||!positive(root.revision))requestError()
 const documents=strictObject(root.documents,['revision','about','terms','privacy','legalReviewed'])
 const home=strictObject(root.home,['revision','announcements','faqs','featuredModelKeys'])
 if(!documents||!home||documents.revision!==root.revision||home.revision!==root.revision||!positive(documents.revision))requestError()
 if(!structuredText(documents.about)||!structuredText(documents.terms)||!structuredText(documents.privacy)||typeof documents.legalReviewed!=='boolean')requestError()
 const announcementValues=strictArray(home.announcements),faqValues=strictArray(home.faqs),featuredValues=strictArray(home.featuredModelKeys)
 if(!announcementValues||!faqValues||!featuredValues||announcementValues.length>20||faqValues.length>50||featuredValues.length>12)requestError()
 const announcementGuids=new Set(),faqGuids=new Set(),featuredKeys=new Set()
 const announcements=announcementValues.map(value=>{const item=strictObject(value,['guid','title','bodyMarkdown','effectiveAt','isVisible','sortOrder']);if(!item||!structuredGuid(item.guid)||announcementGuids.has(item.guid)||!structuredText(item.title,{maxCodepoints:120,maxBytes:480,plain:true})||!structuredText(item.bodyMarkdown,{maxBytes:16384})||!structuredUTC(item.effectiveAt)||typeof item.isVisible!=='boolean'||!structuredSort(item.sortOrder))requestError();announcementGuids.add(item.guid);return{guid:item.guid,title:item.title,body_markdown:item.bodyMarkdown,effective_at:item.effectiveAt,is_visible:item.isVisible,sort_order:item.sortOrder}}).sort(announcementOrder)
 const faqs=faqValues.map(value=>{const item=strictObject(value,['guid','question','answerMarkdown','isVisible','sortOrder']);if(!item||!structuredGuid(item.guid)||faqGuids.has(item.guid)||!structuredText(item.question,{maxCodepoints:200,maxBytes:800,plain:true})||!structuredText(item.answerMarkdown,{maxBytes:16384})||typeof item.isVisible!=='boolean'||!structuredSort(item.sortOrder))requestError();faqGuids.add(item.guid);return{guid:item.guid,question:item.question,answer_markdown:item.answerMarkdown,is_visible:item.isVisible,sort_order:item.sortOrder}}).sort(faqOrder)
 const featured=featuredValues.map(value=>{if(!structuredModelKey(value)||featuredKeys.has(value))requestError();featuredKeys.add(value);return value})
 return{revision:root.revision,documents:{about:documents.about,terms:documents.terms,privacy:documents.privacy,legal_reviewed:documents.legalReviewed},home:{announcements,faqs,featured_model_keys:featured}}
}
export function canonicalStructuredContent(value){return JSON.stringify(canonicalStructuredValue(value))}
export async function hashCanonicalStructuredContent(value,cryptoImpl=globalThis.crypto){if(typeof cryptoImpl?.subtle?.digest!=='function')throw new Error('secure_digest_unavailable');const digest=new Uint8Array(await cryptoImpl.subtle.digest('SHA-256',new TextEncoder().encode(canonicalStructuredContent(value))));return[...digest].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
export async function createStructuredContentValidationProof(value,priceReleaseGuid,result,cryptoImpl=globalThis.crypto){const target=String(priceReleaseGuid);guid(target);if(result?.valid!==true)return null;const canonical=canonicalStructuredContent(value);return Object.freeze({valid:true,revision:value.revision,canonical,contentHash:await hashCanonicalStructuredContent(value,cryptoImpl),priceReleaseGuid:target})}
export function structuredContentValidationProofMatches(proof,value,savedCanonical,priceReleaseGuid){let current;try{current=canonicalStructuredContent(value)}catch{return false}return proof?.valid===true&&proof.revision===value.revision&&proof.canonical===current&&current===savedCanonical&&proof.priceReleaseGuid===String(priceReleaseGuid)&&/^[a-f0-9]{64}$/.test(proof.contentHash)}

const previewError=code=>Object.assign(new Error(code),{code})
export async function loadStructuredContentPreview({revision:requestedRevision,priceReleaseGuid,homeApi,pricingApi,renderMarkdown,signal}={}){
 const requested=revision(requestedRevision),priceGuid=String(priceReleaseGuid);guid(priceGuid)
 if(!homeApi||!pricingApi||typeof renderMarkdown!=='function')requestError()
 const controller=new AbortController(),abort=()=>controller.abort();if(signal?.aborted)controller.abort();else signal?.addEventListener?.('abort',abort,{once:true})
 try{
  let documents,home,pricing
  try{[documents,home,pricing]=await Promise.all([homeApi.getDocumentsDraft({signal:controller.signal}),homeApi.previewHome(requested,{signal:controller.signal}),pricingApi.getRelease(priceGuid,{signal:controller.signal})])}catch(error){controller.abort();throw error}
  if(controller.signal.aborted)throw new DOMException('Aborted','AbortError')
  if(documents?.revision!==requested||home?.revision!==requested||pricing?.release?.guid!==priceGuid||!positive(pricing?.release?.version))throw previewError('preview_generation_mismatch')
  const canonical=canonicalStructuredValue({revision:requested,documents,home}),items=strictArray(pricing.items);if(!items)throw previewError('preview_price_release_mismatch')
  const byKey=new Map();for(const item of items){if(!item||typeof item!=='object')throw previewError('preview_price_release_mismatch');const key=item.modelKey;if(!structuredModelKey(key)||item.releaseVersion!==pricing.release.version)throw previewError('preview_price_release_mismatch');if(byKey.has(key))byKey.set(key,null);else byKey.set(key,item)}
  const featured=canonical.home.featured_model_keys.map(key=>byKey.get(key));if(featured.some(item=>!item))throw previewError('preview_price_release_mismatch')
  const mappedHome={revision:requested,announcements:canonical.home.announcements.map(item=>Object.freeze({guid:item.guid,title:item.title,bodyHtml:renderMarkdown(item.body_markdown),effectiveAt:item.effective_at,isVisible:item.is_visible,sortOrder:item.sort_order})),faqs:canonical.home.faqs.map(item=>Object.freeze({guid:item.guid,question:item.question,answerHtml:renderMarkdown(item.answer_markdown),isVisible:item.is_visible,sortOrder:item.sort_order})),featuredModelKeys:[...canonical.home.featured_model_keys]}
  return Object.freeze({revision:requested,documents:Object.freeze({...canonical.documents}),home:Object.freeze({...mappedHome,announcements:Object.freeze(mappedHome.announcements),faqs:Object.freeze(mappedHome.faqs),featuredModelKeys:Object.freeze(mappedHome.featuredModelKeys)}),priceRelease:Object.freeze({...pricing.release}),featuredModels:Object.freeze(featured.map(item=>Object.freeze({...item})))})
 }finally{signal?.removeEventListener?.('abort',abort)}
}
function safeErrorData(error){const code=error&&typeof error==='object'?Object.getOwnPropertyDescriptor(error,'code')?.value:null,requestId=error&&typeof error==='object'?Object.getOwnPropertyDescriptor(error,'requestId')?.value:null;return{code:typeof code==='string'&&/^[a-z_]{1,64}$/.test(code)?code:'request_failed',requestId:typeof requestId==='string'&&/^[A-Za-z0-9._:-]{1,128}$/.test(requestId)?requestId:null}}
const safe=e=>Object.freeze(safeErrorData(e))
export function createContentPublicationCoordinator({api=publicContentAdminApi,state={},generateKey=createIdempotencyKey}={}){Object.assign(state,{busy:false,error:null,conflict:false,pendingRecovery:false,attempt:null,...state});let pending=null,controller=null,generation=0;const clear=()=>{state.attempt=null;state.pendingRecovery=false};const start=(kind,target,revision,password)=>{if(pending)return pending;if(!positive(revision)||typeof password!=='string'||!password)return Promise.resolve(null);const descriptor={kind,target:String(target),revision};if(state.attempt&&(state.attempt.kind!==kind||state.attempt.target!==descriptor.target||state.attempt.revision!==revision)){clear();state.error=Object.freeze({code:'attempt_binding_changed',requestId:null});return Promise.resolve(null)}if(!state.attempt)state.attempt=Object.freeze({...descriptor,key:generateKey()});const attempt=state.attempt,own=++generation;controller=new AbortController();const ownController=controller;state.busy=true;state.error=null;state.conflict=false;let secret=password,phase='issue';pending=(async()=>{try{const issued=kind==='publish'?await api.issuePublishVerification(revision,secret,target,{signal:ownController.signal}):await api.issueRestoreVerification(target,revision,secret,{signal:ownController.signal});secret=null;if(own!==generation||ownController.signal.aborted)return null;phase='execute';const out=kind==='publish'?await api.publish(revision,target,{ticket:issued.ticket,idempotencyKey:attempt.key,signal:ownController.signal}):await api.restore(target,revision,{ticket:issued.ticket,idempotencyKey:attempt.key,signal:ownController.signal});if(own!==generation||ownController.signal.aborted)return null;clear();return out}catch(e){secret=null;if(own!==generation||ownController.signal.aborted)return null;const details=safeErrorData(e),issueNetwork=phase==='issue'&&details.code==='network_error';state.error=issueNetwork?Object.freeze({code:'action_dependency_unavailable',requestId:details.requestId}):Object.freeze(details);state.conflict=details.code==='revision_conflict';state.pendingRecovery=phase==='execute'&&details.code==='network_error';if(!state.pendingRecovery)state.attempt=null;return null}finally{secret=null;if(own===generation){state.busy=false;pending=null}}})();return pending};return{state,publish:(target,revision,password)=>start('publish',target,revision,password),restore:(target,revision,password)=>start('restore',target,revision,password),abandon(){clear();state.error=null},cancel(){generation++;controller?.abort();controller=null;pending=null;clear();state.busy=false;state.error=null}}}
