const GUID=/^[1-9]\d{0,18}$/
const DECIMAL=/^(0|[1-9][0-9]{0,11})(\.[0-9]{1,8})?$/
const MODEL_KEYS=['guid','model_key','upstream_model_id','display_name','provider','capabilities','context_window','input_price_usd_per_million_tokens','output_price_usd_per_million_tokens','status','revision','last_upstream_check_at','public_display_group','endpoint_types','public_restrictions','price_source','price_reviewer','price_effective_at']
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k))
const positive=v=>Number.isSafeInteger(v)&&v>=1
class InvalidPublicModelAdminResponse extends Error{constructor(){super('invalid_public_model_admin_response')}}
const invalid=()=>{throw new InvalidPublicModelAdminResponse()}
const validCodeList=v=>Array.isArray(v)&&v.every(x=>typeof x==='string')
function header(headers,name){const v=typeof headers?.get==='function'?headers.get(name):headers?.[name]??headers?.[name.toLowerCase()];return typeof v==='string'?v:null}
function metadata(result,status){if(!exact(result,['data','status','headers'])||result.status!==status||header(result.headers,'Cache-Control')!=='no-store'||!header(result.headers,'X-Request-ID')?.trim())invalid();return result.data}
function model(raw){
  if(!exact(raw,MODEL_KEYS)||typeof raw.guid!=='string'||!GUID.test(raw.guid)||typeof raw.model_key!=='string'||typeof raw.upstream_model_id!=='string'||typeof raw.display_name!=='string'||typeof raw.provider!=='string'||!validCodeList(raw.capabilities)||!Number.isSafeInteger(raw.context_window)||raw.context_window<1||!['draft','active','inactive'].includes(raw.status)||!positive(raw.revision)||!(raw.last_upstream_check_at===null||positive(raw.last_upstream_check_at))||!validCodeList(raw.endpoint_types)||!validCodeList(raw.public_restrictions)||typeof raw.public_display_group!=='string'||typeof raw.price_source!=='string'||typeof raw.price_reviewer!=='string'||!(raw.price_effective_at===null||positive(raw.price_effective_at)))invalid()
  for(const key of ['input_price_usd_per_million_tokens','output_price_usd_per_million_tokens'])if(!(raw[key]===null||typeof raw[key]==='string'&&DECIMAL.test(raw[key])))invalid()
  return Object.freeze({guid:raw.guid,modelKey:raw.model_key,upstreamModelId:raw.upstream_model_id,displayName:raw.display_name,provider:raw.provider,capabilities:Object.freeze([...raw.capabilities]),contextWindow:raw.context_window,inputPriceUsdPerMillionTokens:raw.input_price_usd_per_million_tokens,outputPriceUsdPerMillionTokens:raw.output_price_usd_per_million_tokens,status:raw.status,revision:raw.revision,lastUpstreamCheckAt:raw.last_upstream_check_at,publicDisplayGroup:raw.public_display_group,endpointTypes:Object.freeze([...raw.endpoint_types]),publicRestrictions:Object.freeze([...raw.public_restrictions]),priceSource:raw.price_source,priceReviewer:raw.price_reviewer,priceEffectiveAt:raw.price_effective_at})
}
function guid(value){if(typeof value!=='string'||!GUID.test(value))throw new Error('invalid_public_model_admin_request');return encodeURIComponent(value)}
function revision(value){if(!positive(value))throw new Error('invalid_public_model_admin_request');return value}
function reason(value){if(typeof value!=='string'||value!==value.trim()||value.length<1||value.length>200)throw new Error('invalid_public_model_admin_request');return value}
export class PublicModelAdminError extends Error{constructor(code,status=null){super(code==='revision_conflict'?'请求失败，请刷新后重试':'请求失败，请稍后重试');this.name='PublicModelAdminError';this.code=code;this.status=status}}
function mapError(error){if(error?.name==='AbortError')return error;const response=error?.response,status=Number.isInteger(response?.status)?response.status:null,raw=response?.data;const expected=({400:'invalid_request',401:'authentication_required',403:'root_role_required',404:'not_found',409:'conflict',410:'gone',422:'validation_failed',503:'unavailable'})[status];const valid=expected&&header(response?.headers,'Cache-Control')==='no-store'&&header(response?.headers,'X-Request-ID')?.trim()&&exact(raw,['error'])&&exact(raw.error,['code','message','request_id'])&&raw.error.code===expected&&typeof raw.error.message==='string'&&typeof raw.error.request_id==='string'&&raw.error.request_id.trim();if(!valid)return new PublicModelAdminError(status?'request_failed':'network_error',status);return new PublicModelAdminError(status===409?'revision_conflict':({401:'authentication_required',403:'root_required',404:'not_found',410:'gone',503:'unavailable'})[status]??expected,status)}
export function publicModelAdminListResource(filters={}){const allowed=new Set(['search','status','upstreamState','page','pageSize']);if(!filters||typeof filters!=='object'||Object.keys(filters).some(k=>!allowed.has(k)))throw new Error('invalid_public_model_admin_query');const p=new URLSearchParams();if(filters.search!==undefined&&filters.search!==''){if(typeof filters.search!=='string')throw new Error('invalid_public_model_admin_query');p.set('search',filters.search)}if(filters.status!==undefined){if(!['draft','active','inactive'].includes(filters.status))throw new Error('invalid_public_model_admin_query');p.set('status',filters.status)}if(filters.upstreamState!==undefined){if(!['present','missing'].includes(filters.upstreamState))throw new Error('invalid_public_model_admin_query');p.set('upstream_state',filters.upstreamState)}if(filters.page!==undefined){if(!positive(filters.page))throw new Error('invalid_public_model_admin_query');p.set('page',String(filters.page))}if(filters.pageSize!==undefined){if(![20,50,100].includes(filters.pageSize))throw new Error('invalid_public_model_admin_query');p.set('page_size',String(filters.pageSize))}const q=p.toString();return '/admin/v2/public-models'+(q?'?'+q:'')}
async function productionRequest({method,path,body,headers={},signal}){const {authenticatedFetch,getAuthToken}=await import('./request.js');const baseURL=import.meta.env?.VITE_API_BASE??'',url=`${baseURL}${path}`;const requestHeaders={...headers};if(body!==undefined)requestHeaders['Content-Type']='application/json';const token=getAuthToken();if(token)requestHeaders.Authorization=`Bearer ${token}`;const response=method==='GET'?await authenticatedFetch(url,{method,headers:requestHeaders,signal}):await fetch(url,{method,headers:requestHeaders,body:body===undefined?undefined:JSON.stringify(body),credentials:'include',signal});let data=null;if(response.status!==204){try{data=await response.json()}catch{data=null}}const result={data,status:response.status,headers:response.headers};if(!response.ok)throw {response:result};return result}
export function createPublicModelAdminApi({request=productionRequest}={}){
  const run=async(args,status,mapper)=>{try{return mapper(metadata(await request(args),status))}catch(e){if(e instanceof InvalidPublicModelAdminResponse)throw e;throw mapError(e)}}
  return Object.freeze({
    list:(filters={},options={})=>run({method:'GET',path:publicModelAdminListResource(filters),signal:options.signal},200,raw=>{if(!exact(raw,['items','page','page_size','total'])||!Array.isArray(raw.items)||!positive(raw.page)||![20,50,100].includes(raw.page_size)||!Number.isSafeInteger(raw.total)||raw.total<0)invalid();return Object.freeze({items:Object.freeze(raw.items.map(model)),page:raw.page,pageSize:raw.page_size,total:raw.total})}),
    get:(id,options={})=>run({method:'GET',path:`/admin/v2/public-models/${guid(id)}`,signal:options.signal},200,model),
    create:(body,options={})=>run({method:'POST',path:'/admin/v2/public-models',body,signal:options.signal},201,model),
    update:(id,body,options={})=>run({method:'PATCH',path:`/admin/v2/public-models/${guid(id)}`,body,signal:options.signal},200,model),
    activate:(id,expectedRevision,options={})=>run({method:'POST',path:`/admin/v2/public-models/${guid(id)}/activate`,body:{expected_revision:revision(expectedRevision)},signal:options.signal},200,model),
    deactivate:(id,expectedRevision,why,options={})=>run({method:'POST',path:`/admin/v2/public-models/${guid(id)}/deactivate`,body:{expected_revision:revision(expectedRevision),reason:reason(why)},signal:options.signal},200,model),
    getMissing:(options={})=>run({method:'GET',path:'/admin/v2/public-models/missing',signal:options.signal},200,raw=>{if(!exact(raw,['observed_without_configuration','configured_missing_upstream'])||!validCodeList(raw.observed_without_configuration)||!Array.isArray(raw.configured_missing_upstream))invalid();return Object.freeze({observedWithoutConfiguration:Object.freeze([...raw.observed_without_configuration]),configuredMissingUpstream:Object.freeze(raw.configured_missing_upstream.map(model))})}),
    sync:(options={})=>run({method:'POST',path:'/admin/v2/public-models/sync',signal:options.signal},202,raw=>{if(!exact(raw,['accepted'])||raw.accepted!==true)invalid();return Object.freeze({accepted:true})}),
    issueDeleteVerification:({guid:id,expectedRevision,currentPassword,reason:why},options={})=>{if(typeof currentPassword!=='string'||!currentPassword)throw new Error('invalid_public_model_admin_request');const intent={target_guid:String(id),expected_revision:revision(expectedRevision),reason:reason(why)};guid(String(id));return run({method:'POST',path:'/admin/v2/action-verifications',body:{action:'public_models.delete',intent,current_password:currentPassword},signal:options.signal},201,raw=>{if(!exact(raw,['ticket','expires_at'])||typeof raw.ticket!=='string'||!raw.ticket||!positive(raw.expires_at))invalid();return Object.freeze({ticket:raw.ticket,expiresAt:raw.expires_at})})},
    deleteModel:(id,{expectedRevision,reason:why,ticket},options={})=>{if(typeof ticket!=='string'||!ticket)throw new Error('invalid_public_model_admin_request');return run({method:'DELETE',path:`/admin/v2/public-models/${guid(id)}`,body:{expected_revision:revision(expectedRevision),reason:reason(why)},headers:{'X-Action-Ticket':ticket},signal:options.signal},204,raw=>{if(raw!==null&&raw!==undefined&&raw!=='')invalid();return true})},
  })
}
export const publicModelAdminApi=createPublicModelAdminApi()
