import {defineStore} from 'pinia'
import {reactive,toRefs} from 'vue'
import {publicModelAdminApi} from '../api/publicModelAdmin.js'
const LANES=['list','detail','missing'],FLAGS=['createSaving','modelSaving','statusSaving','deleteSaving','syncSaving']
const safeError=e=>Object.freeze({code:typeof e?.code==='string'&&/^[a-z_]{1,64}$/.test(e.code)?e.code:'request_failed',requestId:typeof e?.requestId==='string'&&/^[A-Za-z0-9._:-]{1,128}$/.test(e.requestId)?e.requestId:null})
export function createPublicModelAdminCoordinator({api=publicModelAdminApi,state}={}){
 const v=state??reactive({items:[],page:1,pageSize:20,total:0,detail:null,missing:null,loading:false,error:null});for(const x of LANES){v[`${x}Loading`]??=false;v[`${x}Error`]??=null}for(const x of FLAGS)v[x]??=false;v.mutationError??=null
 const reads=Object.fromEntries(LANES.map(x=>[x,{generation:0,abort:null}])),writes=Object.create(null);let mutationGeneration=0,mutationContext=''
 const refresh=()=>{v.loading=LANES.some(x=>v[`${x}Loading`])||FLAGS.some(x=>v[x]);v.error=v.mutationError??v.detailError??v.listError??v.missingError}
 const begin=lane=>{const o=reads[lane];o.generation++;o.abort?.abort();o.abort=new AbortController();v[`${lane}Loading`]=true;v[`${lane}Error`]=null;refresh();return{lane,generation:o.generation,signal:o.abort.signal}}
 const owns=t=>reads[t.lane].generation===t.generation
 const read=(lane,work,apply)=>{const t=begin(lane);return(async()=>{try{const out=await work(t.signal);if(owns(t))apply(out);return owns(t)?out:null}catch(e){if(owns(t)&&e?.name!=='AbortError')v[`${lane}Error`]=safeError(e);return null}finally{if(owns(t)){v[`${lane}Loading`]=false;reads[lane].abort=null;refresh()}}})()}
 const replace=out=>{v.items=v.items.map(x=>x.guid===out.guid?out:x);if(v.detail?.guid===out.guid)v.detail=out}
 const write=(key,flag,work,apply=replace)=>{const generation=mutationGeneration,existing=writes[key];if(existing?.generation===generation)return existing.promise;const controller=new AbortController();v[flag]=true;v.mutationError=null;v.mutationOperation=key.split(':')[0];refresh();const owns=()=>generation===mutationGeneration;const pending=Promise.resolve().then(()=>work({owns,signal:controller.signal})).then(out=>{if(!owns())return null;apply(out);return out}).catch(e=>{if(owns()&&e?.name!=='AbortError')v.mutationError=safeError(e);return null}).finally(()=>{if(writes[key]?.promise===pending)delete writes[key];if(owns()){v[flag]=false;refresh()}});writes[key]={generation,promise:pending,controller};return pending}
 return{state:v,setMutationContext(context){const next=String(context??'');if(next===mutationContext)return;mutationContext=next;mutationGeneration++;for(const entry of Object.values(writes))entry.controller.abort();for(const flag of FLAGS)v[flag]=false;v.mutationError=null;v.mutationOperation=null;refresh()},clearMutationError(){v.mutationError=null;v.mutationOperation=null;refresh()},cancel(){for(const lane of LANES){reads[lane].generation++;reads[lane].abort?.abort();reads[lane].abort=null;v[`${lane}Loading`]=false}mutationGeneration++;for(const entry of Object.values(writes))entry.controller.abort();for(const flag of FLAGS)v[flag]=false;refresh()},clearDetail(){reads.detail.generation++;reads.detail.abort?.abort();reads.detail.abort=null;v.detail=null;v.detailLoading=false;v.detailError=null;refresh()},load(filters={}){return read('list',s=>api.list(filters,{signal:s}),o=>Object.assign(v,{items:o.items,page:o.page,pageSize:o.pageSize,total:o.total}))},loadDetail(guid){return read('detail',s=>api.get(guid,{signal:s}),o=>{v.detail=o})},loadMissing(){return read('missing',s=>api.getMissing({signal:s}),o=>{v.missing=o})},sync(){return write('sync','syncSaving',({signal})=>api.sync({signal}),()=>{})},create(form,recentlyObservedIds){return write('create','createSaving',({signal})=>api.create(form,{recentlyObservedIds,signal}),o=>{v.items=[o,...v.items];v.total++;v.detail=o})},update(guid,form,current){return write(`update:${guid}`,'modelSaving',({signal})=>api.update(guid,form,{current,signal}))},activate(guid,rev){return write(`status:${guid}`,'statusSaving',({signal})=>api.activate(guid,rev,{signal}))},deactivate(guid,rev,reason){return write(`status:${guid}`,'statusSaving',({signal})=>api.deactivate(guid,rev,reason,{signal}))},remove(input){if(!input||typeof input!=='object')return Promise.resolve(null);const safe=Object.freeze({guid:input.guid,expectedRevision:input.expectedRevision,reason:input.reason});let password=input.currentPassword;try{input.currentPassword=null}catch{}return write(`delete:${safe.guid}`,'deleteSaving',async({owns,signal})=>{let issued,verification={...safe,currentPassword:password};try{issued=await api.issueDeleteVerification(verification,{signal})}finally{verification.currentPassword=null;verification=null;password=null}if(!owns())return null;return api.deleteModel(safe.guid,{expectedRevision:safe.expectedRevision,reason:safe.reason,ticket:issued.ticket},{signal})},()=>{v.items=v.items.filter(x=>x.guid!==safe.guid);v.total=Math.max(0,v.total-1);if(v.detail?.guid===safe.guid)v.detail=null})}}
}
export const usePublicModelAdminStore=defineStore('publicModelAdmin',()=>{const state=reactive({items:[],page:1,pageSize:20,total:0,detail:null,missing:null,loading:false,error:null});const c=createPublicModelAdminCoordinator({state});return{...toRefs(state),...c}})
