import {defineStore} from 'pinia'
import {reactive,toRefs} from 'vue'
import {authSession} from '../api/request.js'
import {rootNotificationsApi} from '../api/rootNotifications.js'

const blank=()=>({active:[],resolved:[],activePage:0,resolvedPage:0,activeTotal:0,resolvedTotal:0,activeLoadingMore:false,resolvedLoadingMore:false,unreadCount:0,loading:false,error:null,mutationError:null,pendingReceipts:{}})
const safeError=error=>Object.freeze({code:typeof error?.code==='string'&&/^[a-z_]{1,64}$/.test(error.code)?error.code:'request_failed',requestId:typeof error?.requestId==='string'&&/^[A-Za-z0-9._:-]{1,128}$/.test(error.requestId)?error.requestId:null})
const rootIdentity=snapshot=>snapshot?.state==='authenticated'&&typeof snapshot.accessToken==='string'&&snapshot.accessToken&&snapshot.user?.role==='root'&&typeof snapshot.user.guid==='string'&&snapshot.user.guid&&typeof snapshot.epoch==='string'&&snapshot.epoch?`${snapshot.epoch}:${snapshot.user.guid}`:null
const dedupe=items=>[...new Map(items.map(item=>[item.guid,item])).values()]

export function createRootNotificationsCoordinator({api=rootNotificationsApi,auth=authSession,state={},setIntervalFn=setInterval,clearIntervalFn=clearInterval,pollMs=30000}={}){
  Object.assign(state,blank(),state)
  let session=0,identity=null,timer=null,latest=Promise.resolve(),refreshSeq=0,unsub=null
  const receiptFacts=new Map(),lanes=Object.fromEntries(['active','resolved','count'].map(key=>[key,{seq:0,controller:null,promise:null}]))
  const receiptControllers=new Set()
  const abortLane=name=>{const lane=lanes[name];lane.seq++;lane.controller?.abort();lane.controller=null;lane.promise=null}
  const reset=()=>{session++;refreshSeq++;for(const name of Object.keys(lanes))abortLane(name);for(const controller of receiptControllers)controller.abort();receiptControllers.clear();receiptFacts.clear();if(timer!==null){clearIntervalFn(timer);timer=null}Object.assign(state,blank())}
  const current=()=>{const captured=auth.capture?.()??{};return{...captured,state:auth.state?.(),accessToken:auth.accessToken?.(),user:auth.user?.()}}
  const authorized=()=>identity!==null&&rootIdentity(current())===identity
  const mergeReceipt=item=>{const fact=receiptFacts.get(item.guid);return fact?Object.freeze({...item,read:item.read||fact.read,acknowledged:item.acknowledged||fact.acknowledged}):item}
  const requestLane=(name,work,apply)=>{const lane=lanes[name],ownSession=session,ownSeq=++lane.seq;lane.controller?.abort();const controller=new AbortController();lane.controller=controller;const promise=(async()=>{try{const value=await work(controller.signal);if(ownSession!==session||ownSeq!==lane.seq)return null;apply(value);return value}catch(error){if(ownSession===session&&ownSeq===lane.seq&&error?.name!=='AbortError')state.error=safeError(error);return null}finally{if(ownSession===session&&ownSeq===lane.seq){lane.controller=null;lane.promise=null}}})();lane.promise=promise;return promise}
  const loadGroup=(name,page,{replace=false}={})=>{if(!['active','resolved'].includes(name)||!Number.isInteger(page)||page<1)return Promise.resolve(null);const flag=`${name}LoadingMore`;if(!replace&&state[flag]&&lanes[name].promise)return lanes[name].promise;state[flag]=!replace;const ownSession=session,expectedSeq=lanes[name].seq+1;return requestLane(name,signal=>api.list({state:name,page,pageSize:20},{signal}),result=>{const incoming=result.items.map(mergeReceipt);state[name]=replace?dedupe(incoming):dedupe([...state[name],...incoming]);state[`${name}Page`]=result.page;state[`${name}Total`]=result.total}).finally(()=>{if(ownSession===session&&lanes[name].seq===expectedSeq)state[flag]=false})}
  const doRefreshUnread=()=>requestLane('count',signal=>api.unreadCount({signal}),count=>{state.unreadCount=count})
  const refreshUnread=()=>authorized()?doRefreshUnread():Promise.resolve(null)
  const doRefresh=()=>{const ownSession=session,ownRefresh=++refreshSeq;state.loading=true;state.error=null;latest=Promise.all([loadGroup('active',1,{replace:true}),loadGroup('resolved',1,{replace:true}),doRefreshUnread()]).finally(()=>{if(ownSession===session&&ownRefresh===refreshSeq)state.loading=false});return latest}
  const refresh=()=>authorized()?doRefresh():Promise.resolve(null)
  const loadMore=name=>{if(!authorized()||!['active','resolved'].includes(name)||state[name].length>=state[`${name}Total`])return Promise.resolve(null);return loadGroup(name,state[`${name}Page`]+1)}
  const applyReceipt=item=>{const previous=[...state.active,...state.resolved].find(value=>value.guid===item.guid),prior=receiptFacts.get(item.guid)??{read:false,acknowledged:false},fact={read:prior.read||item.read,acknowledged:prior.acknowledged||item.acknowledged};receiptFacts.set(item.guid,fact);for(const name of ['active','resolved'])state[name]=state[name].map(value=>value.guid===item.guid?Object.freeze({...item,read:value.read||fact.read,acknowledged:value.acknowledged||fact.acknowledged}):value);if(previous&&!previous.read&&fact.read)state.unreadCount=Math.max(0,state.unreadCount-1);abortLane('count');return[...state.active,...state.resolved].find(value=>value.guid===item.guid)??mergeReceipt(item)}
  const mutate=(kind,id)=>{if(!authorized())return Promise.resolve(null);if(state.pendingReceipts[id]?.[kind])return state.pendingReceipts[id][kind];const controller=new AbortController(),ownSession=session;receiptControllers.add(controller);state.mutationError=null;const pending=(async()=>{try{const item=await api[kind](id,{signal:controller.signal});if(ownSession!==session)return null;return applyReceipt(item)}catch(error){if(ownSession===session&&error?.name!=='AbortError')state.mutationError=safeError(error);return null}finally{receiptControllers.delete(controller);if(ownSession===session&&state.pendingReceipts[id]){delete state.pendingReceipts[id][kind];if(!Object.keys(state.pendingReceipts[id]).length)delete state.pendingReceipts[id]}}})();state.pendingReceipts[id]??={};state.pendingReceipts[id][kind]=pending;return pending}
  const start=snapshot=>{const next=rootIdentity(snapshot);if(!next){if(identity!==null||timer!==null)reset();identity=null;return}if(next===identity)return;reset();identity=next;latest=doRefresh();timer=setIntervalFn(()=>{if(authorized())void doRefreshUnread()},pollMs)}
  unsub=auth.subscribe(start);start(current())
  return{state,refresh,refreshUnread,loadMore,markRead:id=>mutate('markRead',String(id)),acknowledge:id=>mutate('acknowledge',String(id)),ready:()=>latest,clear(){reset();identity=null},dispose(){reset();identity=null;unsub?.();unsub=null}}
}
export const useRootNotificationsStore=defineStore('rootNotifications',()=>{const state=reactive(blank()),coordinator=createRootNotificationsCoordinator({state});return{...toRefs(state),refresh:coordinator.refresh,refreshUnread:coordinator.refreshUnread,loadMore:coordinator.loadMore,markRead:coordinator.markRead,acknowledge:coordinator.acknowledge,clear:coordinator.clear}})
